/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.river.client.models

import dev.river.client.models.BiTile

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param tile 
 * @param valid 
 * @param error 
 * @param raw raw model reply
 */


data class AiBiTilePost200Response (

    @Json(name = "tile")
    val tile: BiTile? = null,

    @Json(name = "valid")
    val valid: kotlin.Boolean? = null,

    @Json(name = "error")
    val error: kotlin.String? = null,

    /* raw model reply */
    @Json(name = "raw")
    val raw: kotlin.String? = null

) {


}

