/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.river.client.models

import dev.river.client.models.BiFilter
import dev.river.client.models.BiTile

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param name 
 * @param updatedAt 
 * @param tiles present on single-dashboard reads only
 * @param filters present on single-dashboard reads only
 * @param theme M5 named color palette for the dashboard's charts (default river)
 * @param updatedBy 
 */


data class BiDashboard (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    /* present on single-dashboard reads only */
    @Json(name = "tiles")
    val tiles: kotlin.collections.List<BiTile>? = null,

    /* present on single-dashboard reads only */
    @Json(name = "filters")
    val filters: kotlin.collections.List<BiFilter>? = null,

    /* M5 named color palette for the dashboard's charts (default river) */
    @Json(name = "theme")
    val theme: BiDashboard.Theme? = null,

    @Json(name = "updated_by")
    val updatedBy: kotlin.String? = null

) {

    /**
     * M5 named color palette for the dashboard's charts (default river)
     *
     * Values: river,sunset,forest,berry,mono
     */
    @JsonClass(generateAdapter = false)
    enum class Theme(val value: kotlin.String) {
        @Json(name = "river") river("river"),
        @Json(name = "sunset") sunset("sunset"),
        @Json(name = "forest") forest("forest"),
        @Json(name = "berry") berry("berry"),
        @Json(name = "mono") mono("mono");
    }

}

