/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.river.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * M5 drill-down — run the tile's stored drill query LIVE (in both modes) with the clicked value bound to its `:param`, plus the usual filter values. 
 *
 * @param tile index into the dashboard's tiles array
 * @param `value` the clicked category value (≤ 256 chars)
 */


data class BiDashboardsIdDataPostRequestDrill (

    /* index into the dashboard's tiles array */
    @Json(name = "tile")
    val tile: kotlin.Int,

    /* the clicked category value (≤ 256 chars) */
    @Json(name = "value")
    val `value`: kotlin.String

) {


}

