/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.river.client.models

import dev.river.client.models.TileData

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param createdAt 
 * @param createdBy 
 * @param tiles 
 */


data class BiDashboardsIdSnapshotGet200ResponseSnapshot (

    @Json(name = "created_at")
    val createdAt: kotlin.String? = null,

    @Json(name = "created_by")
    val createdBy: kotlin.String? = null,

    @Json(name = "tiles")
    val tiles: kotlin.collections.List<TileData>? = null

) {


}

