/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.river.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param createdAt 
 * @param tiles number of tile entries stored
 * @param errors 
 */


data class BiDashboardsIdSnapshotPost200Response (

    @Json(name = "created_at")
    val createdAt: kotlin.String? = null,

    /* number of tile entries stored */
    @Json(name = "tiles")
    val tiles: kotlin.Int? = null,

    @Json(name = "errors")
    val errors: kotlin.Int? = null

) {


}

