/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.river.client.models

import dev.river.client.models.TileData

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param dashboardId 
 * @param generatedAt 
 * @param tiles 
 * @param source M4 — \"snapshot\" responses replay stored results (generated_at is the capture time); \"live\" executed (or cache-served) tile SQL now. 
 * @param drill M5 — present when the request carried `drill`; the clicked tile's drill query result (index = the requested tile)
 */


data class BiDashboardData (

    @Json(name = "dashboard_id")
    val dashboardId: kotlin.String,

    @Json(name = "generated_at")
    val generatedAt: java.time.OffsetDateTime,

    @Json(name = "tiles")
    val tiles: kotlin.collections.List<TileData>,

    /* M4 — \"snapshot\" responses replay stored results (generated_at is the capture time); \"live\" executed (or cache-served) tile SQL now.  */
    @Json(name = "source")
    val source: BiDashboardData.Source? = null,

    /* M5 — present when the request carried `drill`; the clicked tile's drill query result (index = the requested tile) */
    @Json(name = "drill")
    val drill: TileData? = null

) {

    /**
     * M4 — \"snapshot\" responses replay stored results (generated_at is the capture time); \"live\" executed (or cache-served) tile SQL now. 
     *
     * Values: live,snapshot
     */
    @JsonClass(generateAdapter = false)
    enum class Source(val value: kotlin.String) {
        @Json(name = "live") live("live"),
        @Json(name = "snapshot") snapshot("snapshot");
    }

}

