/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.river.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param alias 
 * @param backendType 
 * @param displayName 
 * @param host 
 * @param port 
 * @param database 
 * @param readOnly 
 * @param status 
 * @param tags 
 */


data class ConnectionSummary (

    @Json(name = "alias")
    val alias: kotlin.String? = null,

    @Json(name = "backend_type")
    val backendType: ConnectionSummary.BackendType? = null,

    @Json(name = "display_name")
    val displayName: kotlin.String? = null,

    @Json(name = "host")
    val host: kotlin.String? = null,

    @Json(name = "port")
    val port: kotlin.Int? = null,

    @Json(name = "database")
    val database: kotlin.String? = null,

    @Json(name = "read_only")
    val readOnly: kotlin.Boolean? = null,

    @Json(name = "status")
    val status: ConnectionSummary.Status? = null,

    @Json(name = "tags")
    val tags: kotlin.collections.List<kotlin.String>? = null

) {

    /**
     * 
     *
     * Values: postgres,mysql,sqlite,mongodb
     */
    @JsonClass(generateAdapter = false)
    enum class BackendType(val value: kotlin.String) {
        @Json(name = "postgres") postgres("postgres"),
        @Json(name = "mysql") mysql("mysql"),
        @Json(name = "sqlite") sqlite("sqlite"),
        @Json(name = "mongodb") mongodb("mongodb");
    }
    /**
     * 
     *
     * Values: active,degraded,unreachable,unknown
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "active") active("active"),
        @Json(name = "degraded") degraded("degraded"),
        @Json(name = "unreachable") unreachable("unreachable"),
        @Json(name = "unknown") unknown("unknown");
    }

}

