/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.river.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name 
 * @param targetAlias connection the migration will apply to
 * @param targetSchema postgres namespace the migration applies into
 */


data class DesignerDesignsPostRequest (

    @Json(name = "name")
    val name: kotlin.String,

    /* connection the migration will apply to */
    @Json(name = "target_alias")
    val targetAlias: kotlin.String? = null,

    /* postgres namespace the migration applies into */
    @Json(name = "target_schema")
    val targetSchema: kotlin.String? = null

) {


}

