/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.river.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param name 
 * @param fromTable 
 * @param fromColumns 
 * @param toTable 
 * @param toColumns 
 * @param onDelete 
 * @param onUpdate 
 */


data class DesignerModelRelationshipsInner (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "fromTable")
    val fromTable: kotlin.String,

    @Json(name = "fromColumns")
    val fromColumns: kotlin.collections.List<kotlin.String>,

    @Json(name = "toTable")
    val toTable: kotlin.String,

    @Json(name = "toColumns")
    val toColumns: kotlin.collections.List<kotlin.String>,

    @Json(name = "onDelete")
    val onDelete: DesignerModelRelationshipsInner.OnDelete? = null,

    @Json(name = "onUpdate")
    val onUpdate: DesignerModelRelationshipsInner.OnUpdate? = null

) {

    /**
     * 
     *
     * Values: restrict,cascade,set_null,set_default,no_action
     */
    @JsonClass(generateAdapter = false)
    enum class OnDelete(val value: kotlin.String) {
        @Json(name = "restrict") restrict("restrict"),
        @Json(name = "cascade") cascade("cascade"),
        @Json(name = "set_null") set_null("set_null"),
        @Json(name = "set_default") set_default("set_default"),
        @Json(name = "no_action") no_action("no_action");
    }
    /**
     * 
     *
     * Values: restrict,cascade,set_null,set_default,no_action
     */
    @JsonClass(generateAdapter = false)
    enum class OnUpdate(val value: kotlin.String) {
        @Json(name = "restrict") restrict("restrict"),
        @Json(name = "cascade") cascade("cascade"),
        @Json(name = "set_null") set_null("set_null"),
        @Json(name = "set_default") set_default("set_default"),
        @Json(name = "no_action") no_action("no_action");
    }

}

