/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.river.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param table 
 * @param confirm must equal `table`
 * @param database 
 * @param schema 
 * @param ifExists 
 * @param cascade not supported — fails loud rather than silently skipping dependents
 */


data class TablesAliasDropPostRequest (

    @Json(name = "table")
    val table: kotlin.String,

    /* must equal `table` */
    @Json(name = "confirm")
    val confirm: kotlin.String,

    @Json(name = "database")
    val database: kotlin.String? = null,

    @Json(name = "schema")
    val schema: kotlin.String? = null,

    @Json(name = "if_exists")
    val ifExists: kotlin.Boolean? = false,

    /* not supported — fails loud rather than silently skipping dependents */
    @Json(name = "cascade")
    val cascade: kotlin.Boolean? = false

) {


}

