/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package dev.river.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param table 
 * @param `data` payload ≤ 64 MiB
 * @param format 
 * @param truncate 
 * @param createIfMissing 
 * @param database native database when the alias is a server
 * @param schema native namespace to import into (postgres)
 */


data class ToolsAliasImportPostRequest (

    @Json(name = "table")
    val table: kotlin.String,

    /* payload ≤ 64 MiB */
    @Json(name = "data")
    val `data`: kotlin.String,

    @Json(name = "format")
    val format: ToolsAliasImportPostRequest.Format? = Format.json,

    @Json(name = "truncate")
    val truncate: kotlin.Boolean? = false,

    @Json(name = "create_if_missing")
    val createIfMissing: kotlin.Boolean? = true,

    /* native database when the alias is a server */
    @Json(name = "database")
    val database: kotlin.String? = null,

    /* native namespace to import into (postgres) */
    @Json(name = "schema")
    val schema: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: json,ndjson,csv
     */
    @JsonClass(generateAdapter = false)
    enum class Format(val value: kotlin.String) {
        @Json(name = "json") json("json"),
        @Json(name = "ndjson") ndjson("ndjson"),
        @Json(name = "csv") csv("csv");
    }

}

