// <auto-generated>
/*
 * River REST API
 *
 * Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 
 *
 * The version of the OpenAPI document: 0.10.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using River.Client;

namespace River.Model
{
    /// <summary>
    /// AiConversationsPostRequest
    /// </summary>
    public partial class AiConversationsPostRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AiConversationsPostRequest" /> class.
        /// </summary>
        /// <param name="title">title</param>
        /// <param name="messages">messages</param>
        [JsonConstructor]
        public AiConversationsPostRequest(Option<string?> title = default, Option<List<AiConversationsPostRequestMessagesInner>?> messages = default)
        {
            TitleOption = title;
            MessagesOption = messages;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Title
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TitleOption { get; private set; }

        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        [JsonPropertyName("title")]
        public string? Title { get { return this.TitleOption.Value; } set { this.TitleOption = new(value); } }

        /// <summary>
        /// Used to track the state of Messages
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<AiConversationsPostRequestMessagesInner>?> MessagesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Messages
        /// </summary>
        [JsonPropertyName("messages")]
        public List<AiConversationsPostRequestMessagesInner>? Messages { get { return this.MessagesOption.Value; } set { this.MessagesOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AiConversationsPostRequest {\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Messages: ").Append(Messages).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AiConversationsPostRequest" />
    /// </summary>
    public partial class AiConversationsPostRequestJsonConverter : JsonConverter<AiConversationsPostRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="AiConversationsPostRequestJsonConverter" /> class.
        /// </summary>
        public AiConversationsPostRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="AiConversationsPostRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AiConversationsPostRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> title = default;
            Option<List<AiConversationsPostRequestMessagesInner>?> messages = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "title":
                            title = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "messages":
                            messages = new Option<List<AiConversationsPostRequestMessagesInner>?>(JsonSerializer.Deserialize<List<AiConversationsPostRequestMessagesInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (title.IsSet && title.Value == null)
                throw new ArgumentNullException(nameof(title), "Property is not nullable for class AiConversationsPostRequest.");

            if (messages.IsSet && messages.Value == null)
                throw new ArgumentNullException(nameof(messages), "Property is not nullable for class AiConversationsPostRequest.");

            return new AiConversationsPostRequest(title, messages);
        }

        /// <summary>
        /// Serializes a <see cref="AiConversationsPostRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="aiConversationsPostRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AiConversationsPostRequest aiConversationsPostRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, aiConversationsPostRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AiConversationsPostRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="aiConversationsPostRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AiConversationsPostRequest aiConversationsPostRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (aiConversationsPostRequest.TitleOption.IsSet && aiConversationsPostRequest.Title == null)
                throw new ArgumentNullException(nameof(aiConversationsPostRequest.Title), "Property is required for class AiConversationsPostRequest.");

            if (aiConversationsPostRequest.MessagesOption.IsSet && aiConversationsPostRequest.Messages == null)
                throw new ArgumentNullException(nameof(aiConversationsPostRequest.Messages), "Property is required for class AiConversationsPostRequest.");

            if (aiConversationsPostRequest.TitleOption.IsSet)
                writer.WriteString("title", aiConversationsPostRequest.Title);

            if (aiConversationsPostRequest.MessagesOption.IsSet)
            {
                writer.WritePropertyName("messages");
                JsonSerializer.Serialize(writer, aiConversationsPostRequest.Messages, jsonSerializerOptions);
            }
        }
    }
}
