// <auto-generated>
/*
 * River REST API
 *
 * Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 
 *
 * The version of the OpenAPI document: 0.9.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using River.Client;

namespace River.Model
{
    /// <summary>
    /// AuthPermissionsGet200Response
    /// </summary>
    public partial class AuthPermissionsGet200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthPermissionsGet200Response" /> class.
        /// </summary>
        /// <param name="role">role</param>
        /// <param name="permissions">permissions</param>
        /// <param name="catalog">catalog</param>
        [JsonConstructor]
        public AuthPermissionsGet200Response(Option<string?> role = default, Option<List<string>?> permissions = default, Option<List<AuthPermissionsGet200ResponseCatalogInner>?> catalog = default)
        {
            RoleOption = role;
            PermissionsOption = permissions;
            CatalogOption = catalog;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Role
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RoleOption { get; private set; }

        /// <summary>
        /// Gets or Sets Role
        /// </summary>
        [JsonPropertyName("role")]
        public string? Role { get { return this.RoleOption.Value; } set { this.RoleOption = new(value); } }

        /// <summary>
        /// Used to track the state of Permissions
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> PermissionsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Permissions
        /// </summary>
        [JsonPropertyName("permissions")]
        public List<string>? Permissions { get { return this.PermissionsOption.Value; } set { this.PermissionsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Catalog
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<AuthPermissionsGet200ResponseCatalogInner>?> CatalogOption { get; private set; }

        /// <summary>
        /// Gets or Sets Catalog
        /// </summary>
        [JsonPropertyName("catalog")]
        public List<AuthPermissionsGet200ResponseCatalogInner>? Catalog { get { return this.CatalogOption.Value; } set { this.CatalogOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AuthPermissionsGet200Response {\n");
            sb.Append("  Role: ").Append(Role).Append("\n");
            sb.Append("  Permissions: ").Append(Permissions).Append("\n");
            sb.Append("  Catalog: ").Append(Catalog).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AuthPermissionsGet200Response" />
    /// </summary>
    public partial class AuthPermissionsGet200ResponseJsonConverter : JsonConverter<AuthPermissionsGet200Response>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthPermissionsGet200ResponseJsonConverter" /> class.
        /// </summary>
        public AuthPermissionsGet200ResponseJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="AuthPermissionsGet200Response" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AuthPermissionsGet200Response Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> role = default;
            Option<List<string>?> permissions = default;
            Option<List<AuthPermissionsGet200ResponseCatalogInner>?> catalog = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "role":
                            role = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "permissions":
                            permissions = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "catalog":
                            catalog = new Option<List<AuthPermissionsGet200ResponseCatalogInner>?>(JsonSerializer.Deserialize<List<AuthPermissionsGet200ResponseCatalogInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (role.IsSet && role.Value == null)
                throw new ArgumentNullException(nameof(role), "Property is not nullable for class AuthPermissionsGet200Response.");

            if (permissions.IsSet && permissions.Value == null)
                throw new ArgumentNullException(nameof(permissions), "Property is not nullable for class AuthPermissionsGet200Response.");

            if (catalog.IsSet && catalog.Value == null)
                throw new ArgumentNullException(nameof(catalog), "Property is not nullable for class AuthPermissionsGet200Response.");

            return new AuthPermissionsGet200Response(role, permissions, catalog);
        }

        /// <summary>
        /// Serializes a <see cref="AuthPermissionsGet200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="authPermissionsGet200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AuthPermissionsGet200Response authPermissionsGet200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, authPermissionsGet200Response, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AuthPermissionsGet200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="authPermissionsGet200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AuthPermissionsGet200Response authPermissionsGet200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            if (authPermissionsGet200Response.RoleOption.IsSet && authPermissionsGet200Response.Role == null)
                throw new ArgumentNullException(nameof(authPermissionsGet200Response.Role), "Property is required for class AuthPermissionsGet200Response.");

            if (authPermissionsGet200Response.PermissionsOption.IsSet && authPermissionsGet200Response.Permissions == null)
                throw new ArgumentNullException(nameof(authPermissionsGet200Response.Permissions), "Property is required for class AuthPermissionsGet200Response.");

            if (authPermissionsGet200Response.CatalogOption.IsSet && authPermissionsGet200Response.Catalog == null)
                throw new ArgumentNullException(nameof(authPermissionsGet200Response.Catalog), "Property is required for class AuthPermissionsGet200Response.");

            if (authPermissionsGet200Response.RoleOption.IsSet)
                writer.WriteString("role", authPermissionsGet200Response.Role);

            if (authPermissionsGet200Response.PermissionsOption.IsSet)
            {
                writer.WritePropertyName("permissions");
                JsonSerializer.Serialize(writer, authPermissionsGet200Response.Permissions, jsonSerializerOptions);
            }
            if (authPermissionsGet200Response.CatalogOption.IsSet)
            {
                writer.WritePropertyName("catalog");
                JsonSerializer.Serialize(writer, authPermissionsGet200Response.Catalog, jsonSerializerOptions);
            }
        }
    }
}
