// <auto-generated>
/*
 * River REST API
 *
 * Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 
 *
 * The version of the OpenAPI document: 0.9.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using River.Client;

namespace River.Model
{
    /// <summary>
    /// BiDashboardsPost201Response
    /// </summary>
    public partial class BiDashboardsPost201Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BiDashboardsPost201Response" /> class.
        /// </summary>
        /// <param name="dashboard">dashboard</param>
        [JsonConstructor]
        public BiDashboardsPost201Response(Option<BiDashboard?> dashboard = default)
        {
            DashboardOption = dashboard;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Dashboard
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<BiDashboard?> DashboardOption { get; private set; }

        /// <summary>
        /// Gets or Sets Dashboard
        /// </summary>
        [JsonPropertyName("dashboard")]
        public BiDashboard? Dashboard { get { return this.DashboardOption.Value; } set { this.DashboardOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BiDashboardsPost201Response {\n");
            sb.Append("  Dashboard: ").Append(Dashboard).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="BiDashboardsPost201Response" />
    /// </summary>
    public partial class BiDashboardsPost201ResponseJsonConverter : JsonConverter<BiDashboardsPost201Response>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="BiDashboardsPost201ResponseJsonConverter" /> class.
        /// </summary>
        public BiDashboardsPost201ResponseJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="BiDashboardsPost201Response" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override BiDashboardsPost201Response Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<BiDashboard?> dashboard = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "dashboard":
                            dashboard = new Option<BiDashboard?>(JsonSerializer.Deserialize<BiDashboard>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (dashboard.IsSet && dashboard.Value == null)
                throw new ArgumentNullException(nameof(dashboard), "Property is not nullable for class BiDashboardsPost201Response.");

            return new BiDashboardsPost201Response(dashboard);
        }

        /// <summary>
        /// Serializes a <see cref="BiDashboardsPost201Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="biDashboardsPost201Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, BiDashboardsPost201Response biDashboardsPost201Response, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, biDashboardsPost201Response, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="BiDashboardsPost201Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="biDashboardsPost201Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, BiDashboardsPost201Response biDashboardsPost201Response, JsonSerializerOptions jsonSerializerOptions)
        {
            if (biDashboardsPost201Response.DashboardOption.IsSet && biDashboardsPost201Response.Dashboard == null)
                throw new ArgumentNullException(nameof(biDashboardsPost201Response.Dashboard), "Property is required for class BiDashboardsPost201Response.");

            if (biDashboardsPost201Response.DashboardOption.IsSet)
            {
                writer.WritePropertyName("dashboard");
                JsonSerializer.Serialize(writer, biDashboardsPost201Response.Dashboard, jsonSerializerOptions);
            }
        }
    }
}
