// <auto-generated>
/*
 * River REST API
 *
 * Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 
 *
 * The version of the OpenAPI document: 0.9.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using River.Client;

namespace River.Model
{
    /// <summary>
    /// M3 dashboard filter declaration. &#x60;param&#x60; names the &#x60;:param&#x60; token tile queries bind to; daterange filters bind &#x60;&lt;param&gt;_from&#x60; / &#x60;&lt;param&gt;_to&#x60; (ISO dates). Values live on the client; this is the authoring contract. 
    /// </summary>
    public partial class BiFilter : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BiFilter" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="param">identifier bound to tile :param tokens</param>
        /// <param name="kind">kind</param>
        /// <param name="label">label</param>
        /// <param name="options">category choices (declared by the author; cross-filter writes these too)</param>
        /// <param name="default">category default (used by the background warmer)</param>
        [JsonConstructor]
        public BiFilter(string id, string param, KindEnum kind, Option<string?> label = default, Option<List<string>?> options = default, Option<string?> @default = default)
        {
            Id = id;
            Param = param;
            Kind = kind;
            LabelOption = label;
            OptionsOption = options;
            DefaultOption = @default;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Kind
        /// </summary>
        public enum KindEnum
        {
            /// <summary>
            /// Enum Category for value: category
            /// </summary>
            Category = 1,

            /// <summary>
            /// Enum Daterange for value: daterange
            /// </summary>
            Daterange = 2
        }

        /// <summary>
        /// Returns a <see cref="KindEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static KindEnum KindEnumFromString(string value)
        {
            if (value.Equals("category"))
                return KindEnum.Category;

            if (value.Equals("daterange"))
                return KindEnum.Daterange;

            throw new NotImplementedException($"Could not convert value to type KindEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="KindEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static KindEnum? KindEnumFromStringOrDefault(string value)
        {
            if (value.Equals("category"))
                return KindEnum.Category;

            if (value.Equals("daterange"))
                return KindEnum.Daterange;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="KindEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string KindEnumToJsonValue(KindEnum value)
        {
            if (value == KindEnum.Category)
                return "category";

            if (value == KindEnum.Daterange)
                return "daterange";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Kind
        /// </summary>
        [JsonPropertyName("kind")]
        public KindEnum Kind { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>
        /// identifier bound to tile :param tokens
        /// </summary>
        /// <value>identifier bound to tile :param tokens</value>
        [JsonPropertyName("param")]
        public string Param { get; set; }

        /// <summary>
        /// Used to track the state of Label
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LabelOption { get; private set; }

        /// <summary>
        /// Gets or Sets Label
        /// </summary>
        [JsonPropertyName("label")]
        public string? Label { get { return this.LabelOption.Value; } set { this.LabelOption = new(value); } }

        /// <summary>
        /// Used to track the state of Options
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> OptionsOption { get; private set; }

        /// <summary>
        /// category choices (declared by the author; cross-filter writes these too)
        /// </summary>
        /// <value>category choices (declared by the author; cross-filter writes these too)</value>
        [JsonPropertyName("options")]
        public List<string>? Options { get { return this.OptionsOption.Value; } set { this.OptionsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Default
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DefaultOption { get; private set; }

        /// <summary>
        /// category default (used by the background warmer)
        /// </summary>
        /// <value>category default (used by the background warmer)</value>
        [JsonPropertyName("default")]
        public string? Default { get { return this.DefaultOption.Value; } set { this.DefaultOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BiFilter {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Param: ").Append(Param).Append("\n");
            sb.Append("  Kind: ").Append(Kind).Append("\n");
            sb.Append("  Label: ").Append(Label).Append("\n");
            sb.Append("  Options: ").Append(Options).Append("\n");
            sb.Append("  Default: ").Append(Default).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="BiFilter" />
    /// </summary>
    public partial class BiFilterJsonConverter : JsonConverter<BiFilter>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="BiFilterJsonConverter" /> class.
        /// </summary>
        public BiFilterJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="BiFilter" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override BiFilter Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> id = default;
            Option<string?> param = default;
            Option<BiFilter.KindEnum?> kind = default;
            Option<string?> label = default;
            Option<List<string>?> options = default;
            Option<string?> varDefault = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "param":
                            param = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "kind":
                            string? kindRawValue = utf8JsonReader.GetString();
                            if (kindRawValue != null)
                            {
                                BiFilter.KindEnum? kindValue = BiFilter.KindEnumFromStringOrDefault(kindRawValue);
                                if (kindValue == null)
                                    throw new JsonException();
                                kind = new Option<BiFilter.KindEnum?>(kindValue);
                            }
                            break;
                        case "label":
                            label = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "options":
                            options = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "default":
                            varDefault = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class BiFilter.", nameof(id));

            if (!param.IsSet)
                throw new ArgumentException("Property is required for class BiFilter.", nameof(param));

            if (!kind.IsSet)
                throw new ArgumentException("Property is required for class BiFilter.", nameof(kind));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class BiFilter.");

            if (param.IsSet && param.Value == null)
                throw new ArgumentNullException(nameof(param), "Property is not nullable for class BiFilter.");

            if (kind.IsSet && kind.Value == null)
                throw new ArgumentNullException(nameof(kind), "Property is not nullable for class BiFilter.");

            if (label.IsSet && label.Value == null)
                throw new ArgumentNullException(nameof(label), "Property is not nullable for class BiFilter.");

            if (options.IsSet && options.Value == null)
                throw new ArgumentNullException(nameof(options), "Property is not nullable for class BiFilter.");

            if (varDefault.IsSet && varDefault.Value == null)
                throw new ArgumentNullException(nameof(varDefault), "Property is not nullable for class BiFilter.");

            return new BiFilter(id.Value!, param.Value!, kind.Value!.Value!, label, options, varDefault);
        }

        /// <summary>
        /// Serializes a <see cref="BiFilter" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="biFilter"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, BiFilter biFilter, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, biFilter, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="BiFilter" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="biFilter"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, BiFilter biFilter, JsonSerializerOptions jsonSerializerOptions)
        {
            if (biFilter.Id == null)
                throw new ArgumentNullException(nameof(biFilter.Id), "Property is required for class BiFilter.");

            if (biFilter.Param == null)
                throw new ArgumentNullException(nameof(biFilter.Param), "Property is required for class BiFilter.");

            if (biFilter.LabelOption.IsSet && biFilter.Label == null)
                throw new ArgumentNullException(nameof(biFilter.Label), "Property is required for class BiFilter.");

            if (biFilter.OptionsOption.IsSet && biFilter.Options == null)
                throw new ArgumentNullException(nameof(biFilter.Options), "Property is required for class BiFilter.");

            if (biFilter.DefaultOption.IsSet && biFilter.Default == null)
                throw new ArgumentNullException(nameof(biFilter.Default), "Property is required for class BiFilter.");

            writer.WriteString("id", biFilter.Id);

            writer.WriteString("param", biFilter.Param);

            var kindRawValue = BiFilter.KindEnumToJsonValue(biFilter.Kind);
            writer.WriteString("kind", kindRawValue);
            if (biFilter.LabelOption.IsSet)
                writer.WriteString("label", biFilter.Label);

            if (biFilter.OptionsOption.IsSet)
            {
                writer.WritePropertyName("options");
                JsonSerializer.Serialize(writer, biFilter.Options, jsonSerializerOptions);
            }
            if (biFilter.DefaultOption.IsSet)
                writer.WriteString("default", biFilter.Default);
        }
    }
}
