// <auto-generated>
/*
 * River REST API
 *
 * Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 
 *
 * The version of the OpenAPI document: 0.10.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using River.Client;

namespace River.Model
{
    /// <summary>
    /// ConnectionsPostRequest
    /// </summary>
    public partial class ConnectionsPostRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConnectionsPostRequest" /> class.
        /// </summary>
        /// <param name="alias">alias</param>
        /// <param name="backendType">backendType</param>
        /// <param name="database">database</param>
        /// <param name="host">host</param>
        /// <param name="port">port</param>
        /// <param name="username">username</param>
        /// <param name="password">password</param>
        /// <param name="readOnly">readOnly</param>
        [JsonConstructor]
        public ConnectionsPostRequest(string alias, string backendType, string database, Option<string?> host = default, Option<int?> port = default, Option<string?> username = default, Option<string?> password = default, Option<bool?> readOnly = default)
        {
            Alias = alias;
            BackendType = backendType;
            Database = database;
            HostOption = host;
            PortOption = port;
            UsernameOption = username;
            PasswordOption = password;
            ReadOnlyOption = readOnly;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Alias
        /// </summary>
        [JsonPropertyName("alias")]
        public string Alias { get; set; }

        /// <summary>
        /// Gets or Sets BackendType
        /// </summary>
        [JsonPropertyName("backend_type")]
        public string BackendType { get; set; }

        /// <summary>
        /// Gets or Sets Database
        /// </summary>
        [JsonPropertyName("database")]
        public string Database { get; set; }

        /// <summary>
        /// Used to track the state of Host
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> HostOption { get; private set; }

        /// <summary>
        /// Gets or Sets Host
        /// </summary>
        [JsonPropertyName("host")]
        public string? Host { get { return this.HostOption.Value; } set { this.HostOption = new(value); } }

        /// <summary>
        /// Used to track the state of Port
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> PortOption { get; private set; }

        /// <summary>
        /// Gets or Sets Port
        /// </summary>
        [JsonPropertyName("port")]
        public int? Port { get { return this.PortOption.Value; } set { this.PortOption = new(value); } }

        /// <summary>
        /// Used to track the state of Username
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> UsernameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Username
        /// </summary>
        [JsonPropertyName("username")]
        public string? Username { get { return this.UsernameOption.Value; } set { this.UsernameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Password
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PasswordOption { get; private set; }

        /// <summary>
        /// Gets or Sets Password
        /// </summary>
        [JsonPropertyName("password")]
        public string? Password { get { return this.PasswordOption.Value; } set { this.PasswordOption = new(value); } }

        /// <summary>
        /// Used to track the state of ReadOnly
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> ReadOnlyOption { get; private set; }

        /// <summary>
        /// Gets or Sets ReadOnly
        /// </summary>
        [JsonPropertyName("read_only")]
        public bool? ReadOnly { get { return this.ReadOnlyOption.Value; } set { this.ReadOnlyOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ConnectionsPostRequest {\n");
            sb.Append("  Alias: ").Append(Alias).Append("\n");
            sb.Append("  BackendType: ").Append(BackendType).Append("\n");
            sb.Append("  Database: ").Append(Database).Append("\n");
            sb.Append("  Host: ").Append(Host).Append("\n");
            sb.Append("  Port: ").Append(Port).Append("\n");
            sb.Append("  Username: ").Append(Username).Append("\n");
            sb.Append("  Password: ").Append(Password).Append("\n");
            sb.Append("  ReadOnly: ").Append(ReadOnly).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ConnectionsPostRequest" />
    /// </summary>
    public partial class ConnectionsPostRequestJsonConverter : JsonConverter<ConnectionsPostRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ConnectionsPostRequestJsonConverter" /> class.
        /// </summary>
        public ConnectionsPostRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ConnectionsPostRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ConnectionsPostRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> alias = default;
            Option<string?> backendType = default;
            Option<string?> database = default;
            Option<string?> host = default;
            Option<int?> port = default;
            Option<string?> username = default;
            Option<string?> password = default;
            Option<bool?> readOnly = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "alias":
                            alias = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "backend_type":
                            backendType = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "database":
                            database = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "host":
                            host = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "port":
                            port = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "username":
                            username = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "password":
                            password = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "read_only":
                            readOnly = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!alias.IsSet)
                throw new ArgumentException("Property is required for class ConnectionsPostRequest.", nameof(alias));

            if (!backendType.IsSet)
                throw new ArgumentException("Property is required for class ConnectionsPostRequest.", nameof(backendType));

            if (!database.IsSet)
                throw new ArgumentException("Property is required for class ConnectionsPostRequest.", nameof(database));

            if (alias.IsSet && alias.Value == null)
                throw new ArgumentNullException(nameof(alias), "Property is not nullable for class ConnectionsPostRequest.");

            if (backendType.IsSet && backendType.Value == null)
                throw new ArgumentNullException(nameof(backendType), "Property is not nullable for class ConnectionsPostRequest.");

            if (database.IsSet && database.Value == null)
                throw new ArgumentNullException(nameof(database), "Property is not nullable for class ConnectionsPostRequest.");

            if (host.IsSet && host.Value == null)
                throw new ArgumentNullException(nameof(host), "Property is not nullable for class ConnectionsPostRequest.");

            if (port.IsSet && port.Value == null)
                throw new ArgumentNullException(nameof(port), "Property is not nullable for class ConnectionsPostRequest.");

            if (username.IsSet && username.Value == null)
                throw new ArgumentNullException(nameof(username), "Property is not nullable for class ConnectionsPostRequest.");

            if (password.IsSet && password.Value == null)
                throw new ArgumentNullException(nameof(password), "Property is not nullable for class ConnectionsPostRequest.");

            if (readOnly.IsSet && readOnly.Value == null)
                throw new ArgumentNullException(nameof(readOnly), "Property is not nullable for class ConnectionsPostRequest.");

            return new ConnectionsPostRequest(alias.Value!, backendType.Value!, database.Value!, host, port, username, password, readOnly);
        }

        /// <summary>
        /// Serializes a <see cref="ConnectionsPostRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="connectionsPostRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ConnectionsPostRequest connectionsPostRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, connectionsPostRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ConnectionsPostRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="connectionsPostRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ConnectionsPostRequest connectionsPostRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (connectionsPostRequest.Alias == null)
                throw new ArgumentNullException(nameof(connectionsPostRequest.Alias), "Property is required for class ConnectionsPostRequest.");

            if (connectionsPostRequest.BackendType == null)
                throw new ArgumentNullException(nameof(connectionsPostRequest.BackendType), "Property is required for class ConnectionsPostRequest.");

            if (connectionsPostRequest.Database == null)
                throw new ArgumentNullException(nameof(connectionsPostRequest.Database), "Property is required for class ConnectionsPostRequest.");

            if (connectionsPostRequest.HostOption.IsSet && connectionsPostRequest.Host == null)
                throw new ArgumentNullException(nameof(connectionsPostRequest.Host), "Property is required for class ConnectionsPostRequest.");

            if (connectionsPostRequest.UsernameOption.IsSet && connectionsPostRequest.Username == null)
                throw new ArgumentNullException(nameof(connectionsPostRequest.Username), "Property is required for class ConnectionsPostRequest.");

            if (connectionsPostRequest.PasswordOption.IsSet && connectionsPostRequest.Password == null)
                throw new ArgumentNullException(nameof(connectionsPostRequest.Password), "Property is required for class ConnectionsPostRequest.");

            writer.WriteString("alias", connectionsPostRequest.Alias);

            writer.WriteString("backend_type", connectionsPostRequest.BackendType);

            writer.WriteString("database", connectionsPostRequest.Database);

            if (connectionsPostRequest.HostOption.IsSet)
                writer.WriteString("host", connectionsPostRequest.Host);

            if (connectionsPostRequest.PortOption.IsSet)
                writer.WriteNumber("port", connectionsPostRequest.PortOption.Value!.Value);

            if (connectionsPostRequest.UsernameOption.IsSet)
                writer.WriteString("username", connectionsPostRequest.Username);

            if (connectionsPostRequest.PasswordOption.IsSet)
                writer.WriteString("password", connectionsPostRequest.Password);

            if (connectionsPostRequest.ReadOnlyOption.IsSet)
                writer.WriteBoolean("read_only", connectionsPostRequest.ReadOnlyOption.Value!.Value);
        }
    }
}
