// <auto-generated>
/*
 * River REST API
 *
 * Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 
 *
 * The version of the OpenAPI document: 0.10.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using River.Client;

namespace River.Model
{
    /// <summary>
    /// DesignerDesignsPostRequest
    /// </summary>
    public partial class DesignerDesignsPostRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DesignerDesignsPostRequest" /> class.
        /// </summary>
        /// <param name="name">name</param>
        /// <param name="targetAlias">connection the migration will apply to</param>
        /// <param name="targetSchema">postgres namespace the migration applies into</param>
        [JsonConstructor]
        public DesignerDesignsPostRequest(string name, Option<string?> targetAlias = default, Option<string?> targetSchema = default)
        {
            Name = name;
            TargetAliasOption = targetAlias;
            TargetSchemaOption = targetSchema;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Used to track the state of TargetAlias
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TargetAliasOption { get; private set; }

        /// <summary>
        /// connection the migration will apply to
        /// </summary>
        /// <value>connection the migration will apply to</value>
        [JsonPropertyName("target_alias")]
        public string? TargetAlias { get { return this.TargetAliasOption.Value; } set { this.TargetAliasOption = new(value); } }

        /// <summary>
        /// Used to track the state of TargetSchema
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TargetSchemaOption { get; private set; }

        /// <summary>
        /// postgres namespace the migration applies into
        /// </summary>
        /// <value>postgres namespace the migration applies into</value>
        [JsonPropertyName("target_schema")]
        public string? TargetSchema { get { return this.TargetSchemaOption.Value; } set { this.TargetSchemaOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DesignerDesignsPostRequest {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  TargetAlias: ").Append(TargetAlias).Append("\n");
            sb.Append("  TargetSchema: ").Append(TargetSchema).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DesignerDesignsPostRequest" />
    /// </summary>
    public partial class DesignerDesignsPostRequestJsonConverter : JsonConverter<DesignerDesignsPostRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="DesignerDesignsPostRequestJsonConverter" /> class.
        /// </summary>
        public DesignerDesignsPostRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="DesignerDesignsPostRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override DesignerDesignsPostRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<string?> targetAlias = default;
            Option<string?> targetSchema = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "target_alias":
                            targetAlias = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "target_schema":
                            targetSchema = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class DesignerDesignsPostRequest.", nameof(name));

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class DesignerDesignsPostRequest.");

            if (targetAlias.IsSet && targetAlias.Value == null)
                throw new ArgumentNullException(nameof(targetAlias), "Property is not nullable for class DesignerDesignsPostRequest.");

            if (targetSchema.IsSet && targetSchema.Value == null)
                throw new ArgumentNullException(nameof(targetSchema), "Property is not nullable for class DesignerDesignsPostRequest.");

            return new DesignerDesignsPostRequest(name.Value!, targetAlias, targetSchema);
        }

        /// <summary>
        /// Serializes a <see cref="DesignerDesignsPostRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="designerDesignsPostRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, DesignerDesignsPostRequest designerDesignsPostRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, designerDesignsPostRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="DesignerDesignsPostRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="designerDesignsPostRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, DesignerDesignsPostRequest designerDesignsPostRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (designerDesignsPostRequest.Name == null)
                throw new ArgumentNullException(nameof(designerDesignsPostRequest.Name), "Property is required for class DesignerDesignsPostRequest.");

            if (designerDesignsPostRequest.TargetAliasOption.IsSet && designerDesignsPostRequest.TargetAlias == null)
                throw new ArgumentNullException(nameof(designerDesignsPostRequest.TargetAlias), "Property is required for class DesignerDesignsPostRequest.");

            if (designerDesignsPostRequest.TargetSchemaOption.IsSet && designerDesignsPostRequest.TargetSchema == null)
                throw new ArgumentNullException(nameof(designerDesignsPostRequest.TargetSchema), "Property is required for class DesignerDesignsPostRequest.");

            writer.WriteString("name", designerDesignsPostRequest.Name);

            if (designerDesignsPostRequest.TargetAliasOption.IsSet)
                writer.WriteString("target_alias", designerDesignsPostRequest.TargetAlias);

            if (designerDesignsPostRequest.TargetSchemaOption.IsSet)
                writer.WriteString("target_schema", designerDesignsPostRequest.TargetSchema);
        }
    }
}
