// <auto-generated>
/*
 * River REST API
 *
 * Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 
 *
 * The version of the OpenAPI document: 0.9.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using River.Client;

namespace River.Model
{
    /// <summary>
    /// JobsPostRequest
    /// </summary>
    public partial class JobsPostRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="JobsPostRequest" /> class.
        /// </summary>
        /// <param name="name">name</param>
        /// <param name="taskType">sql | notebook</param>
        /// <param name="description">description</param>
        /// <param name="schedule">cron expression</param>
        /// <param name="sql">sql</param>
        /// <param name="connectionAlias">required for sql tasks</param>
        /// <param name="notebookId">required for notebook tasks</param>
        [JsonConstructor]
        public JobsPostRequest(string name, string taskType, Option<string?> description = default, Option<string?> schedule = default, Option<string?> sql = default, Option<string?> connectionAlias = default, Option<string?> notebookId = default)
        {
            Name = name;
            TaskType = taskType;
            DescriptionOption = description;
            ScheduleOption = schedule;
            SqlOption = sql;
            ConnectionAliasOption = connectionAlias;
            NotebookIdOption = notebookId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// sql | notebook
        /// </summary>
        /// <value>sql | notebook</value>
        [JsonPropertyName("task_type")]
        public string TaskType { get; set; }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [JsonPropertyName("description")]
        public string? Description { get { return this.DescriptionOption.Value; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of Schedule
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ScheduleOption { get; private set; }

        /// <summary>
        /// cron expression
        /// </summary>
        /// <value>cron expression</value>
        [JsonPropertyName("schedule")]
        public string? Schedule { get { return this.ScheduleOption.Value; } set { this.ScheduleOption = new(value); } }

        /// <summary>
        /// Used to track the state of Sql
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SqlOption { get; private set; }

        /// <summary>
        /// Gets or Sets Sql
        /// </summary>
        [JsonPropertyName("sql")]
        public string? Sql { get { return this.SqlOption.Value; } set { this.SqlOption = new(value); } }

        /// <summary>
        /// Used to track the state of ConnectionAlias
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ConnectionAliasOption { get; private set; }

        /// <summary>
        /// required for sql tasks
        /// </summary>
        /// <value>required for sql tasks</value>
        [JsonPropertyName("connection_alias")]
        public string? ConnectionAlias { get { return this.ConnectionAliasOption.Value; } set { this.ConnectionAliasOption = new(value); } }

        /// <summary>
        /// Used to track the state of NotebookId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NotebookIdOption { get; private set; }

        /// <summary>
        /// required for notebook tasks
        /// </summary>
        /// <value>required for notebook tasks</value>
        [JsonPropertyName("notebook_id")]
        public string? NotebookId { get { return this.NotebookIdOption.Value; } set { this.NotebookIdOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class JobsPostRequest {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  TaskType: ").Append(TaskType).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Schedule: ").Append(Schedule).Append("\n");
            sb.Append("  Sql: ").Append(Sql).Append("\n");
            sb.Append("  ConnectionAlias: ").Append(ConnectionAlias).Append("\n");
            sb.Append("  NotebookId: ").Append(NotebookId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="JobsPostRequest" />
    /// </summary>
    public partial class JobsPostRequestJsonConverter : JsonConverter<JobsPostRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="JobsPostRequestJsonConverter" /> class.
        /// </summary>
        public JobsPostRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="JobsPostRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override JobsPostRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<string?> taskType = default;
            Option<string?> description = default;
            Option<string?> schedule = default;
            Option<string?> sql = default;
            Option<string?> connectionAlias = default;
            Option<string?> notebookId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "task_type":
                            taskType = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "schedule":
                            schedule = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "sql":
                            sql = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "connection_alias":
                            connectionAlias = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "notebook_id":
                            notebookId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class JobsPostRequest.", nameof(name));

            if (!taskType.IsSet)
                throw new ArgumentException("Property is required for class JobsPostRequest.", nameof(taskType));

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class JobsPostRequest.");

            if (taskType.IsSet && taskType.Value == null)
                throw new ArgumentNullException(nameof(taskType), "Property is not nullable for class JobsPostRequest.");

            if (description.IsSet && description.Value == null)
                throw new ArgumentNullException(nameof(description), "Property is not nullable for class JobsPostRequest.");

            if (schedule.IsSet && schedule.Value == null)
                throw new ArgumentNullException(nameof(schedule), "Property is not nullable for class JobsPostRequest.");

            if (sql.IsSet && sql.Value == null)
                throw new ArgumentNullException(nameof(sql), "Property is not nullable for class JobsPostRequest.");

            if (connectionAlias.IsSet && connectionAlias.Value == null)
                throw new ArgumentNullException(nameof(connectionAlias), "Property is not nullable for class JobsPostRequest.");

            if (notebookId.IsSet && notebookId.Value == null)
                throw new ArgumentNullException(nameof(notebookId), "Property is not nullable for class JobsPostRequest.");

            return new JobsPostRequest(name.Value!, taskType.Value!, description, schedule, sql, connectionAlias, notebookId);
        }

        /// <summary>
        /// Serializes a <see cref="JobsPostRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="jobsPostRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, JobsPostRequest jobsPostRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, jobsPostRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="JobsPostRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="jobsPostRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, JobsPostRequest jobsPostRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (jobsPostRequest.Name == null)
                throw new ArgumentNullException(nameof(jobsPostRequest.Name), "Property is required for class JobsPostRequest.");

            if (jobsPostRequest.TaskType == null)
                throw new ArgumentNullException(nameof(jobsPostRequest.TaskType), "Property is required for class JobsPostRequest.");

            if (jobsPostRequest.DescriptionOption.IsSet && jobsPostRequest.Description == null)
                throw new ArgumentNullException(nameof(jobsPostRequest.Description), "Property is required for class JobsPostRequest.");

            if (jobsPostRequest.ScheduleOption.IsSet && jobsPostRequest.Schedule == null)
                throw new ArgumentNullException(nameof(jobsPostRequest.Schedule), "Property is required for class JobsPostRequest.");

            if (jobsPostRequest.SqlOption.IsSet && jobsPostRequest.Sql == null)
                throw new ArgumentNullException(nameof(jobsPostRequest.Sql), "Property is required for class JobsPostRequest.");

            if (jobsPostRequest.ConnectionAliasOption.IsSet && jobsPostRequest.ConnectionAlias == null)
                throw new ArgumentNullException(nameof(jobsPostRequest.ConnectionAlias), "Property is required for class JobsPostRequest.");

            if (jobsPostRequest.NotebookIdOption.IsSet && jobsPostRequest.NotebookId == null)
                throw new ArgumentNullException(nameof(jobsPostRequest.NotebookId), "Property is required for class JobsPostRequest.");

            writer.WriteString("name", jobsPostRequest.Name);

            writer.WriteString("task_type", jobsPostRequest.TaskType);

            if (jobsPostRequest.DescriptionOption.IsSet)
                writer.WriteString("description", jobsPostRequest.Description);

            if (jobsPostRequest.ScheduleOption.IsSet)
                writer.WriteString("schedule", jobsPostRequest.Schedule);

            if (jobsPostRequest.SqlOption.IsSet)
                writer.WriteString("sql", jobsPostRequest.Sql);

            if (jobsPostRequest.ConnectionAliasOption.IsSet)
                writer.WriteString("connection_alias", jobsPostRequest.ConnectionAlias);

            if (jobsPostRequest.NotebookIdOption.IsSet)
                writer.WriteString("notebook_id", jobsPostRequest.NotebookId);
        }
    }
}
