// <auto-generated>
/*
 * River REST API
 *
 * Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 
 *
 * The version of the OpenAPI document: 0.10.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using River.Client;

namespace River.Model
{
    /// <summary>
    /// JobsIdPutRequest
    /// </summary>
    public partial class JobsIdPutRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="JobsIdPutRequest" /> class.
        /// </summary>
        /// <param name="name">name</param>
        /// <param name="description">description</param>
        /// <param name="schedule">schedule</param>
        /// <param name="sql">sql</param>
        /// <param name="connectionAlias">connectionAlias</param>
        /// <param name="notebookId">notebookId</param>
        [JsonConstructor]
        public JobsIdPutRequest(Option<string?> name = default, Option<string?> description = default, Option<string?> schedule = default, Option<string?> sql = default, Option<string?> connectionAlias = default, Option<string?> notebookId = default)
        {
            NameOption = name;
            DescriptionOption = description;
            ScheduleOption = schedule;
            SqlOption = sql;
            ConnectionAliasOption = connectionAlias;
            NotebookIdOption = notebookId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption.Value; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [JsonPropertyName("description")]
        public string? Description { get { return this.DescriptionOption.Value; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of Schedule
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ScheduleOption { get; private set; }

        /// <summary>
        /// Gets or Sets Schedule
        /// </summary>
        [JsonPropertyName("schedule")]
        public string? Schedule { get { return this.ScheduleOption.Value; } set { this.ScheduleOption = new(value); } }

        /// <summary>
        /// Used to track the state of Sql
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SqlOption { get; private set; }

        /// <summary>
        /// Gets or Sets Sql
        /// </summary>
        [JsonPropertyName("sql")]
        public string? Sql { get { return this.SqlOption.Value; } set { this.SqlOption = new(value); } }

        /// <summary>
        /// Used to track the state of ConnectionAlias
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ConnectionAliasOption { get; private set; }

        /// <summary>
        /// Gets or Sets ConnectionAlias
        /// </summary>
        [JsonPropertyName("connection_alias")]
        public string? ConnectionAlias { get { return this.ConnectionAliasOption.Value; } set { this.ConnectionAliasOption = new(value); } }

        /// <summary>
        /// Used to track the state of NotebookId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NotebookIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets NotebookId
        /// </summary>
        [JsonPropertyName("notebook_id")]
        public string? NotebookId { get { return this.NotebookIdOption.Value; } set { this.NotebookIdOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class JobsIdPutRequest {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Schedule: ").Append(Schedule).Append("\n");
            sb.Append("  Sql: ").Append(Sql).Append("\n");
            sb.Append("  ConnectionAlias: ").Append(ConnectionAlias).Append("\n");
            sb.Append("  NotebookId: ").Append(NotebookId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="JobsIdPutRequest" />
    /// </summary>
    public partial class JobsIdPutRequestJsonConverter : JsonConverter<JobsIdPutRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="JobsIdPutRequestJsonConverter" /> class.
        /// </summary>
        public JobsIdPutRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="JobsIdPutRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override JobsIdPutRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<string?> description = default;
            Option<string?> schedule = default;
            Option<string?> sql = default;
            Option<string?> connectionAlias = default;
            Option<string?> notebookId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "schedule":
                            schedule = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "sql":
                            sql = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "connection_alias":
                            connectionAlias = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "notebook_id":
                            notebookId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class JobsIdPutRequest.");

            if (description.IsSet && description.Value == null)
                throw new ArgumentNullException(nameof(description), "Property is not nullable for class JobsIdPutRequest.");

            if (schedule.IsSet && schedule.Value == null)
                throw new ArgumentNullException(nameof(schedule), "Property is not nullable for class JobsIdPutRequest.");

            if (sql.IsSet && sql.Value == null)
                throw new ArgumentNullException(nameof(sql), "Property is not nullable for class JobsIdPutRequest.");

            if (connectionAlias.IsSet && connectionAlias.Value == null)
                throw new ArgumentNullException(nameof(connectionAlias), "Property is not nullable for class JobsIdPutRequest.");

            if (notebookId.IsSet && notebookId.Value == null)
                throw new ArgumentNullException(nameof(notebookId), "Property is not nullable for class JobsIdPutRequest.");

            return new JobsIdPutRequest(name, description, schedule, sql, connectionAlias, notebookId);
        }

        /// <summary>
        /// Serializes a <see cref="JobsIdPutRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="jobsIdPutRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, JobsIdPutRequest jobsIdPutRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, jobsIdPutRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="JobsIdPutRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="jobsIdPutRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, JobsIdPutRequest jobsIdPutRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (jobsIdPutRequest.NameOption.IsSet && jobsIdPutRequest.Name == null)
                throw new ArgumentNullException(nameof(jobsIdPutRequest.Name), "Property is required for class JobsIdPutRequest.");

            if (jobsIdPutRequest.DescriptionOption.IsSet && jobsIdPutRequest.Description == null)
                throw new ArgumentNullException(nameof(jobsIdPutRequest.Description), "Property is required for class JobsIdPutRequest.");

            if (jobsIdPutRequest.ScheduleOption.IsSet && jobsIdPutRequest.Schedule == null)
                throw new ArgumentNullException(nameof(jobsIdPutRequest.Schedule), "Property is required for class JobsIdPutRequest.");

            if (jobsIdPutRequest.SqlOption.IsSet && jobsIdPutRequest.Sql == null)
                throw new ArgumentNullException(nameof(jobsIdPutRequest.Sql), "Property is required for class JobsIdPutRequest.");

            if (jobsIdPutRequest.ConnectionAliasOption.IsSet && jobsIdPutRequest.ConnectionAlias == null)
                throw new ArgumentNullException(nameof(jobsIdPutRequest.ConnectionAlias), "Property is required for class JobsIdPutRequest.");

            if (jobsIdPutRequest.NotebookIdOption.IsSet && jobsIdPutRequest.NotebookId == null)
                throw new ArgumentNullException(nameof(jobsIdPutRequest.NotebookId), "Property is required for class JobsIdPutRequest.");

            if (jobsIdPutRequest.NameOption.IsSet)
                writer.WriteString("name", jobsIdPutRequest.Name);

            if (jobsIdPutRequest.DescriptionOption.IsSet)
                writer.WriteString("description", jobsIdPutRequest.Description);

            if (jobsIdPutRequest.ScheduleOption.IsSet)
                writer.WriteString("schedule", jobsIdPutRequest.Schedule);

            if (jobsIdPutRequest.SqlOption.IsSet)
                writer.WriteString("sql", jobsIdPutRequest.Sql);

            if (jobsIdPutRequest.ConnectionAliasOption.IsSet)
                writer.WriteString("connection_alias", jobsIdPutRequest.ConnectionAlias);

            if (jobsIdPutRequest.NotebookIdOption.IsSet)
                writer.WriteString("notebook_id", jobsIdPutRequest.NotebookId);
        }
    }
}
