// <auto-generated>
/*
 * River REST API
 *
 * Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 
 *
 * The version of the OpenAPI document: 0.9.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using River.Client;

namespace River.Model
{
    /// <summary>
    /// QueryResultSubQueriesInner
    /// </summary>
    public partial class QueryResultSubQueriesInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QueryResultSubQueriesInner" /> class.
        /// </summary>
        /// <param name="alias">alias</param>
        /// <param name="nativeQuery">nativeQuery</param>
        [JsonConstructor]
        public QueryResultSubQueriesInner(Option<string?> alias = default, Option<string?> nativeQuery = default)
        {
            AliasOption = alias;
            NativeQueryOption = nativeQuery;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Alias
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AliasOption { get; private set; }

        /// <summary>
        /// Gets or Sets Alias
        /// </summary>
        [JsonPropertyName("alias")]
        public string? Alias { get { return this.AliasOption.Value; } set { this.AliasOption = new(value); } }

        /// <summary>
        /// Used to track the state of NativeQuery
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NativeQueryOption { get; private set; }

        /// <summary>
        /// Gets or Sets NativeQuery
        /// </summary>
        [JsonPropertyName("native_query")]
        public string? NativeQuery { get { return this.NativeQueryOption.Value; } set { this.NativeQueryOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class QueryResultSubQueriesInner {\n");
            sb.Append("  Alias: ").Append(Alias).Append("\n");
            sb.Append("  NativeQuery: ").Append(NativeQuery).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="QueryResultSubQueriesInner" />
    /// </summary>
    public partial class QueryResultSubQueriesInnerJsonConverter : JsonConverter<QueryResultSubQueriesInner>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="QueryResultSubQueriesInnerJsonConverter" /> class.
        /// </summary>
        public QueryResultSubQueriesInnerJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="QueryResultSubQueriesInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override QueryResultSubQueriesInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> alias = default;
            Option<string?> nativeQuery = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "alias":
                            alias = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "native_query":
                            nativeQuery = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (alias.IsSet && alias.Value == null)
                throw new ArgumentNullException(nameof(alias), "Property is not nullable for class QueryResultSubQueriesInner.");

            if (nativeQuery.IsSet && nativeQuery.Value == null)
                throw new ArgumentNullException(nameof(nativeQuery), "Property is not nullable for class QueryResultSubQueriesInner.");

            return new QueryResultSubQueriesInner(alias, nativeQuery);
        }

        /// <summary>
        /// Serializes a <see cref="QueryResultSubQueriesInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="queryResultSubQueriesInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, QueryResultSubQueriesInner queryResultSubQueriesInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, queryResultSubQueriesInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="QueryResultSubQueriesInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="queryResultSubQueriesInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, QueryResultSubQueriesInner queryResultSubQueriesInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (queryResultSubQueriesInner.AliasOption.IsSet && queryResultSubQueriesInner.Alias == null)
                throw new ArgumentNullException(nameof(queryResultSubQueriesInner.Alias), "Property is required for class QueryResultSubQueriesInner.");

            if (queryResultSubQueriesInner.NativeQueryOption.IsSet && queryResultSubQueriesInner.NativeQuery == null)
                throw new ArgumentNullException(nameof(queryResultSubQueriesInner.NativeQuery), "Property is required for class QueryResultSubQueriesInner.");

            if (queryResultSubQueriesInner.AliasOption.IsSet)
                writer.WriteString("alias", queryResultSubQueriesInner.Alias);

            if (queryResultSubQueriesInner.NativeQueryOption.IsSet)
                writer.WriteString("native_query", queryResultSubQueriesInner.NativeQuery);
        }
    }
}
