// <auto-generated>
/*
 * River REST API
 *
 * Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 
 *
 * The version of the OpenAPI document: 0.10.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using River.Client;

namespace River.Model
{
    /// <summary>
    /// QueryStreamPostRequest
    /// </summary>
    public partial class QueryStreamPostRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QueryStreamPostRequest" /> class.
        /// </summary>
        /// <param name="sql">sql</param>
        [JsonConstructor]
        public QueryStreamPostRequest(string sql)
        {
            Sql = sql;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Sql
        /// </summary>
        [JsonPropertyName("sql")]
        public string Sql { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class QueryStreamPostRequest {\n");
            sb.Append("  Sql: ").Append(Sql).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="QueryStreamPostRequest" />
    /// </summary>
    public partial class QueryStreamPostRequestJsonConverter : JsonConverter<QueryStreamPostRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="QueryStreamPostRequestJsonConverter" /> class.
        /// </summary>
        public QueryStreamPostRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="QueryStreamPostRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override QueryStreamPostRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> sql = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "sql":
                            sql = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!sql.IsSet)
                throw new ArgumentException("Property is required for class QueryStreamPostRequest.", nameof(sql));

            if (sql.IsSet && sql.Value == null)
                throw new ArgumentNullException(nameof(sql), "Property is not nullable for class QueryStreamPostRequest.");

            return new QueryStreamPostRequest(sql.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="QueryStreamPostRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="queryStreamPostRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, QueryStreamPostRequest queryStreamPostRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, queryStreamPostRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="QueryStreamPostRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="queryStreamPostRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, QueryStreamPostRequest queryStreamPostRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (queryStreamPostRequest.Sql == null)
                throw new ArgumentNullException(nameof(queryStreamPostRequest.Sql), "Property is required for class QueryStreamPostRequest.");

            writer.WriteString("sql", queryStreamPostRequest.Sql);
        }
    }
}
