// <auto-generated>
/*
 * River REST API
 *
 * Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 
 *
 * The version of the OpenAPI document: 0.9.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using River.Client;

namespace River.Model
{
    /// <summary>
    /// SchemaDesc
    /// </summary>
    public partial class SchemaDesc : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SchemaDesc" /> class.
        /// </summary>
        /// <param name="alias">alias</param>
        /// <param name="backend">backend</param>
        /// <param name="introspectedAt">introspectedAt</param>
        /// <param name="sampled">sampled</param>
        /// <param name="tables">tables</param>
        [JsonConstructor]
        public SchemaDesc(Option<string?> alias = default, Option<string?> backend = default, Option<string?> introspectedAt = default, Option<bool?> sampled = default, Option<List<SchemaDescTablesInner>?> tables = default)
        {
            AliasOption = alias;
            BackendOption = backend;
            IntrospectedAtOption = introspectedAt;
            SampledOption = sampled;
            TablesOption = tables;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Alias
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AliasOption { get; private set; }

        /// <summary>
        /// Gets or Sets Alias
        /// </summary>
        [JsonPropertyName("alias")]
        public string? Alias { get { return this.AliasOption.Value; } set { this.AliasOption = new(value); } }

        /// <summary>
        /// Used to track the state of Backend
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> BackendOption { get; private set; }

        /// <summary>
        /// Gets or Sets Backend
        /// </summary>
        [JsonPropertyName("backend")]
        public string? Backend { get { return this.BackendOption.Value; } set { this.BackendOption = new(value); } }

        /// <summary>
        /// Used to track the state of IntrospectedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IntrospectedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets IntrospectedAt
        /// </summary>
        [JsonPropertyName("introspected_at")]
        public string? IntrospectedAt { get { return this.IntrospectedAtOption.Value; } set { this.IntrospectedAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of Sampled
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> SampledOption { get; private set; }

        /// <summary>
        /// Gets or Sets Sampled
        /// </summary>
        [JsonPropertyName("sampled")]
        public bool? Sampled { get { return this.SampledOption.Value; } set { this.SampledOption = new(value); } }

        /// <summary>
        /// Used to track the state of Tables
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<SchemaDescTablesInner>?> TablesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Tables
        /// </summary>
        [JsonPropertyName("tables")]
        public List<SchemaDescTablesInner>? Tables { get { return this.TablesOption.Value; } set { this.TablesOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SchemaDesc {\n");
            sb.Append("  Alias: ").Append(Alias).Append("\n");
            sb.Append("  Backend: ").Append(Backend).Append("\n");
            sb.Append("  IntrospectedAt: ").Append(IntrospectedAt).Append("\n");
            sb.Append("  Sampled: ").Append(Sampled).Append("\n");
            sb.Append("  Tables: ").Append(Tables).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SchemaDesc" />
    /// </summary>
    public partial class SchemaDescJsonConverter : JsonConverter<SchemaDesc>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="SchemaDescJsonConverter" /> class.
        /// </summary>
        public SchemaDescJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="SchemaDesc" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SchemaDesc Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> alias = default;
            Option<string?> backend = default;
            Option<string?> introspectedAt = default;
            Option<bool?> sampled = default;
            Option<List<SchemaDescTablesInner>?> tables = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "alias":
                            alias = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "backend":
                            backend = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "introspected_at":
                            introspectedAt = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "sampled":
                            sampled = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "tables":
                            tables = new Option<List<SchemaDescTablesInner>?>(JsonSerializer.Deserialize<List<SchemaDescTablesInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (alias.IsSet && alias.Value == null)
                throw new ArgumentNullException(nameof(alias), "Property is not nullable for class SchemaDesc.");

            if (backend.IsSet && backend.Value == null)
                throw new ArgumentNullException(nameof(backend), "Property is not nullable for class SchemaDesc.");

            if (introspectedAt.IsSet && introspectedAt.Value == null)
                throw new ArgumentNullException(nameof(introspectedAt), "Property is not nullable for class SchemaDesc.");

            if (sampled.IsSet && sampled.Value == null)
                throw new ArgumentNullException(nameof(sampled), "Property is not nullable for class SchemaDesc.");

            if (tables.IsSet && tables.Value == null)
                throw new ArgumentNullException(nameof(tables), "Property is not nullable for class SchemaDesc.");

            return new SchemaDesc(alias, backend, introspectedAt, sampled, tables);
        }

        /// <summary>
        /// Serializes a <see cref="SchemaDesc" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="schemaDesc"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SchemaDesc schemaDesc, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, schemaDesc, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SchemaDesc" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="schemaDesc"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SchemaDesc schemaDesc, JsonSerializerOptions jsonSerializerOptions)
        {
            if (schemaDesc.AliasOption.IsSet && schemaDesc.Alias == null)
                throw new ArgumentNullException(nameof(schemaDesc.Alias), "Property is required for class SchemaDesc.");

            if (schemaDesc.BackendOption.IsSet && schemaDesc.Backend == null)
                throw new ArgumentNullException(nameof(schemaDesc.Backend), "Property is required for class SchemaDesc.");

            if (schemaDesc.IntrospectedAtOption.IsSet && schemaDesc.IntrospectedAt == null)
                throw new ArgumentNullException(nameof(schemaDesc.IntrospectedAt), "Property is required for class SchemaDesc.");

            if (schemaDesc.TablesOption.IsSet && schemaDesc.Tables == null)
                throw new ArgumentNullException(nameof(schemaDesc.Tables), "Property is required for class SchemaDesc.");

            if (schemaDesc.AliasOption.IsSet)
                writer.WriteString("alias", schemaDesc.Alias);

            if (schemaDesc.BackendOption.IsSet)
                writer.WriteString("backend", schemaDesc.Backend);

            if (schemaDesc.IntrospectedAtOption.IsSet)
                writer.WriteString("introspected_at", schemaDesc.IntrospectedAt);

            if (schemaDesc.SampledOption.IsSet)
                writer.WriteBoolean("sampled", schemaDesc.SampledOption.Value!.Value);

            if (schemaDesc.TablesOption.IsSet)
            {
                writer.WritePropertyName("tables");
                JsonSerializer.Serialize(writer, schemaDesc.Tables, jsonSerializerOptions);
            }
        }
    }
}
