// <auto-generated>
/*
 * River REST API
 *
 * Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 
 *
 * The version of the OpenAPI document: 0.10.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using River.Client;

namespace River.Model
{
    /// <summary>
    /// ToolsAliasExportPostRequest
    /// </summary>
    public partial class ToolsAliasExportPostRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ToolsAliasExportPostRequest" /> class.
        /// </summary>
        /// <param name="table">table</param>
        /// <param name="format">format (default to FormatEnum.Json)</param>
        /// <param name="database">native database when the alias is a server</param>
        /// <param name="schema">native namespace the table lives in (postgres)</param>
        [JsonConstructor]
        public ToolsAliasExportPostRequest(string table, Option<FormatEnum?> format = default, Option<string?> database = default, Option<string?> schema = default)
        {
            Table = table;
            FormatOption = format;
            DatabaseOption = database;
            SchemaOption = schema;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Format
        /// </summary>
        public enum FormatEnum
        {
            /// <summary>
            /// Enum Json for value: json
            /// </summary>
            Json = 1,

            /// <summary>
            /// Enum Ndjson for value: ndjson
            /// </summary>
            Ndjson = 2,

            /// <summary>
            /// Enum Csv for value: csv
            /// </summary>
            Csv = 3
        }

        /// <summary>
        /// Returns a <see cref="FormatEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static FormatEnum FormatEnumFromString(string value)
        {
            if (value.Equals("json"))
                return FormatEnum.Json;

            if (value.Equals("ndjson"))
                return FormatEnum.Ndjson;

            if (value.Equals("csv"))
                return FormatEnum.Csv;

            throw new NotImplementedException($"Could not convert value to type FormatEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="FormatEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static FormatEnum? FormatEnumFromStringOrDefault(string value)
        {
            if (value.Equals("json"))
                return FormatEnum.Json;

            if (value.Equals("ndjson"))
                return FormatEnum.Ndjson;

            if (value.Equals("csv"))
                return FormatEnum.Csv;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="FormatEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string FormatEnumToJsonValue(FormatEnum? value)
        {
            if (value == FormatEnum.Json)
                return "json";

            if (value == FormatEnum.Ndjson)
                return "ndjson";

            if (value == FormatEnum.Csv)
                return "csv";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Format
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<FormatEnum?> FormatOption { get; private set; }

        /// <summary>
        /// Gets or Sets Format
        /// </summary>
        [JsonPropertyName("format")]
        public FormatEnum? Format { get { return this.FormatOption.Value; } set { this.FormatOption = new(value); } }

        /// <summary>
        /// Gets or Sets Table
        /// </summary>
        [JsonPropertyName("table")]
        public string Table { get; set; }

        /// <summary>
        /// Used to track the state of Database
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DatabaseOption { get; private set; }

        /// <summary>
        /// native database when the alias is a server
        /// </summary>
        /// <value>native database when the alias is a server</value>
        [JsonPropertyName("database")]
        public string? Database { get { return this.DatabaseOption.Value; } set { this.DatabaseOption = new(value); } }

        /// <summary>
        /// Used to track the state of Schema
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SchemaOption { get; private set; }

        /// <summary>
        /// native namespace the table lives in (postgres)
        /// </summary>
        /// <value>native namespace the table lives in (postgres)</value>
        [JsonPropertyName("schema")]
        public string? Schema { get { return this.SchemaOption.Value; } set { this.SchemaOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ToolsAliasExportPostRequest {\n");
            sb.Append("  Table: ").Append(Table).Append("\n");
            sb.Append("  Format: ").Append(Format).Append("\n");
            sb.Append("  Database: ").Append(Database).Append("\n");
            sb.Append("  Schema: ").Append(Schema).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ToolsAliasExportPostRequest" />
    /// </summary>
    public partial class ToolsAliasExportPostRequestJsonConverter : JsonConverter<ToolsAliasExportPostRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ToolsAliasExportPostRequestJsonConverter" /> class.
        /// </summary>
        public ToolsAliasExportPostRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ToolsAliasExportPostRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ToolsAliasExportPostRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> table = default;
            Option<ToolsAliasExportPostRequest.FormatEnum?> format = default;
            Option<string?> database = default;
            Option<string?> schema = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "table":
                            table = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "format":
                            string? formatRawValue = utf8JsonReader.GetString();
                            if (formatRawValue != null)
                            {
                                ToolsAliasExportPostRequest.FormatEnum? formatValue = ToolsAliasExportPostRequest.FormatEnumFromStringOrDefault(formatRawValue);
                                if (formatValue == null)
                                    throw new JsonException();
                                format = new Option<ToolsAliasExportPostRequest.FormatEnum?>(formatValue);
                            }
                            break;
                        case "database":
                            database = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "schema":
                            schema = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!table.IsSet)
                throw new ArgumentException("Property is required for class ToolsAliasExportPostRequest.", nameof(table));

            if (table.IsSet && table.Value == null)
                throw new ArgumentNullException(nameof(table), "Property is not nullable for class ToolsAliasExportPostRequest.");

            if (format.IsSet && format.Value == null)
                throw new ArgumentNullException(nameof(format), "Property is not nullable for class ToolsAliasExportPostRequest.");

            if (database.IsSet && database.Value == null)
                throw new ArgumentNullException(nameof(database), "Property is not nullable for class ToolsAliasExportPostRequest.");

            if (schema.IsSet && schema.Value == null)
                throw new ArgumentNullException(nameof(schema), "Property is not nullable for class ToolsAliasExportPostRequest.");

            return new ToolsAliasExportPostRequest(table.Value!, format, database, schema);
        }

        /// <summary>
        /// Serializes a <see cref="ToolsAliasExportPostRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="toolsAliasExportPostRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ToolsAliasExportPostRequest toolsAliasExportPostRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, toolsAliasExportPostRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ToolsAliasExportPostRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="toolsAliasExportPostRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ToolsAliasExportPostRequest toolsAliasExportPostRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (toolsAliasExportPostRequest.Table == null)
                throw new ArgumentNullException(nameof(toolsAliasExportPostRequest.Table), "Property is required for class ToolsAliasExportPostRequest.");

            if (toolsAliasExportPostRequest.DatabaseOption.IsSet && toolsAliasExportPostRequest.Database == null)
                throw new ArgumentNullException(nameof(toolsAliasExportPostRequest.Database), "Property is required for class ToolsAliasExportPostRequest.");

            if (toolsAliasExportPostRequest.SchemaOption.IsSet && toolsAliasExportPostRequest.Schema == null)
                throw new ArgumentNullException(nameof(toolsAliasExportPostRequest.Schema), "Property is required for class ToolsAliasExportPostRequest.");

            writer.WriteString("table", toolsAliasExportPostRequest.Table);

            var formatRawValue = ToolsAliasExportPostRequest.FormatEnumToJsonValue(toolsAliasExportPostRequest.FormatOption.Value!.Value);
            writer.WriteString("format", formatRawValue);
            if (toolsAliasExportPostRequest.DatabaseOption.IsSet)
                writer.WriteString("database", toolsAliasExportPostRequest.Database);

            if (toolsAliasExportPostRequest.SchemaOption.IsSet)
                writer.WriteString("schema", toolsAliasExportPostRequest.Schema);
        }
    }
}
