// <auto-generated>
/*
 * River REST API
 *
 * Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 
 *
 * The version of the OpenAPI document: 0.10.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using River.Client;

namespace River.Model
{
    /// <summary>
    /// ToolsAliasImportPostRequest
    /// </summary>
    public partial class ToolsAliasImportPostRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ToolsAliasImportPostRequest" /> class.
        /// </summary>
        /// <param name="table">table</param>
        /// <param name="data">payload ≤ 64 MiB</param>
        /// <param name="format">format (default to FormatEnum.Json)</param>
        /// <param name="truncate">truncate (default to false)</param>
        /// <param name="createIfMissing">createIfMissing (default to true)</param>
        /// <param name="database">native database when the alias is a server</param>
        /// <param name="schema">native namespace to import into (postgres)</param>
        [JsonConstructor]
        public ToolsAliasImportPostRequest(string table, string data, Option<FormatEnum?> format = default, Option<bool?> truncate = default, Option<bool?> createIfMissing = default, Option<string?> database = default, Option<string?> schema = default)
        {
            Table = table;
            Data = data;
            FormatOption = format;
            TruncateOption = truncate;
            CreateIfMissingOption = createIfMissing;
            DatabaseOption = database;
            SchemaOption = schema;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Format
        /// </summary>
        public enum FormatEnum
        {
            /// <summary>
            /// Enum Json for value: json
            /// </summary>
            Json = 1,

            /// <summary>
            /// Enum Ndjson for value: ndjson
            /// </summary>
            Ndjson = 2,

            /// <summary>
            /// Enum Csv for value: csv
            /// </summary>
            Csv = 3
        }

        /// <summary>
        /// Returns a <see cref="FormatEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static FormatEnum FormatEnumFromString(string value)
        {
            if (value.Equals("json"))
                return FormatEnum.Json;

            if (value.Equals("ndjson"))
                return FormatEnum.Ndjson;

            if (value.Equals("csv"))
                return FormatEnum.Csv;

            throw new NotImplementedException($"Could not convert value to type FormatEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="FormatEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static FormatEnum? FormatEnumFromStringOrDefault(string value)
        {
            if (value.Equals("json"))
                return FormatEnum.Json;

            if (value.Equals("ndjson"))
                return FormatEnum.Ndjson;

            if (value.Equals("csv"))
                return FormatEnum.Csv;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="FormatEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string FormatEnumToJsonValue(FormatEnum? value)
        {
            if (value == FormatEnum.Json)
                return "json";

            if (value == FormatEnum.Ndjson)
                return "ndjson";

            if (value == FormatEnum.Csv)
                return "csv";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Format
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<FormatEnum?> FormatOption { get; private set; }

        /// <summary>
        /// Gets or Sets Format
        /// </summary>
        [JsonPropertyName("format")]
        public FormatEnum? Format { get { return this.FormatOption.Value; } set { this.FormatOption = new(value); } }

        /// <summary>
        /// Gets or Sets Table
        /// </summary>
        [JsonPropertyName("table")]
        public string Table { get; set; }

        /// <summary>
        /// payload ≤ 64 MiB
        /// </summary>
        /// <value>payload ≤ 64 MiB</value>
        [JsonPropertyName("data")]
        public string Data { get; set; }

        /// <summary>
        /// Used to track the state of Truncate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> TruncateOption { get; private set; }

        /// <summary>
        /// Gets or Sets Truncate
        /// </summary>
        [JsonPropertyName("truncate")]
        public bool? Truncate { get { return this.TruncateOption.Value; } set { this.TruncateOption = new(value); } }

        /// <summary>
        /// Used to track the state of CreateIfMissing
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> CreateIfMissingOption { get; private set; }

        /// <summary>
        /// Gets or Sets CreateIfMissing
        /// </summary>
        [JsonPropertyName("create_if_missing")]
        public bool? CreateIfMissing { get { return this.CreateIfMissingOption.Value; } set { this.CreateIfMissingOption = new(value); } }

        /// <summary>
        /// Used to track the state of Database
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DatabaseOption { get; private set; }

        /// <summary>
        /// native database when the alias is a server
        /// </summary>
        /// <value>native database when the alias is a server</value>
        [JsonPropertyName("database")]
        public string? Database { get { return this.DatabaseOption.Value; } set { this.DatabaseOption = new(value); } }

        /// <summary>
        /// Used to track the state of Schema
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SchemaOption { get; private set; }

        /// <summary>
        /// native namespace to import into (postgres)
        /// </summary>
        /// <value>native namespace to import into (postgres)</value>
        [JsonPropertyName("schema")]
        public string? Schema { get { return this.SchemaOption.Value; } set { this.SchemaOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ToolsAliasImportPostRequest {\n");
            sb.Append("  Table: ").Append(Table).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  Format: ").Append(Format).Append("\n");
            sb.Append("  Truncate: ").Append(Truncate).Append("\n");
            sb.Append("  CreateIfMissing: ").Append(CreateIfMissing).Append("\n");
            sb.Append("  Database: ").Append(Database).Append("\n");
            sb.Append("  Schema: ").Append(Schema).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ToolsAliasImportPostRequest" />
    /// </summary>
    public partial class ToolsAliasImportPostRequestJsonConverter : JsonConverter<ToolsAliasImportPostRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ToolsAliasImportPostRequestJsonConverter" /> class.
        /// </summary>
        public ToolsAliasImportPostRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ToolsAliasImportPostRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ToolsAliasImportPostRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> table = default;
            Option<string?> data = default;
            Option<ToolsAliasImportPostRequest.FormatEnum?> format = default;
            Option<bool?> truncate = default;
            Option<bool?> createIfMissing = default;
            Option<string?> database = default;
            Option<string?> schema = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "table":
                            table = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "data":
                            data = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "format":
                            string? formatRawValue = utf8JsonReader.GetString();
                            if (formatRawValue != null)
                            {
                                ToolsAliasImportPostRequest.FormatEnum? formatValue = ToolsAliasImportPostRequest.FormatEnumFromStringOrDefault(formatRawValue);
                                if (formatValue == null)
                                    throw new JsonException();
                                format = new Option<ToolsAliasImportPostRequest.FormatEnum?>(formatValue);
                            }
                            break;
                        case "truncate":
                            truncate = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "create_if_missing":
                            createIfMissing = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "database":
                            database = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "schema":
                            schema = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!table.IsSet)
                throw new ArgumentException("Property is required for class ToolsAliasImportPostRequest.", nameof(table));

            if (!data.IsSet)
                throw new ArgumentException("Property is required for class ToolsAliasImportPostRequest.", nameof(data));

            if (table.IsSet && table.Value == null)
                throw new ArgumentNullException(nameof(table), "Property is not nullable for class ToolsAliasImportPostRequest.");

            if (data.IsSet && data.Value == null)
                throw new ArgumentNullException(nameof(data), "Property is not nullable for class ToolsAliasImportPostRequest.");

            if (format.IsSet && format.Value == null)
                throw new ArgumentNullException(nameof(format), "Property is not nullable for class ToolsAliasImportPostRequest.");

            if (truncate.IsSet && truncate.Value == null)
                throw new ArgumentNullException(nameof(truncate), "Property is not nullable for class ToolsAliasImportPostRequest.");

            if (createIfMissing.IsSet && createIfMissing.Value == null)
                throw new ArgumentNullException(nameof(createIfMissing), "Property is not nullable for class ToolsAliasImportPostRequest.");

            if (database.IsSet && database.Value == null)
                throw new ArgumentNullException(nameof(database), "Property is not nullable for class ToolsAliasImportPostRequest.");

            if (schema.IsSet && schema.Value == null)
                throw new ArgumentNullException(nameof(schema), "Property is not nullable for class ToolsAliasImportPostRequest.");

            return new ToolsAliasImportPostRequest(table.Value!, data.Value!, format, truncate, createIfMissing, database, schema);
        }

        /// <summary>
        /// Serializes a <see cref="ToolsAliasImportPostRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="toolsAliasImportPostRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ToolsAliasImportPostRequest toolsAliasImportPostRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, toolsAliasImportPostRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ToolsAliasImportPostRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="toolsAliasImportPostRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ToolsAliasImportPostRequest toolsAliasImportPostRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (toolsAliasImportPostRequest.Table == null)
                throw new ArgumentNullException(nameof(toolsAliasImportPostRequest.Table), "Property is required for class ToolsAliasImportPostRequest.");

            if (toolsAliasImportPostRequest.Data == null)
                throw new ArgumentNullException(nameof(toolsAliasImportPostRequest.Data), "Property is required for class ToolsAliasImportPostRequest.");

            if (toolsAliasImportPostRequest.DatabaseOption.IsSet && toolsAliasImportPostRequest.Database == null)
                throw new ArgumentNullException(nameof(toolsAliasImportPostRequest.Database), "Property is required for class ToolsAliasImportPostRequest.");

            if (toolsAliasImportPostRequest.SchemaOption.IsSet && toolsAliasImportPostRequest.Schema == null)
                throw new ArgumentNullException(nameof(toolsAliasImportPostRequest.Schema), "Property is required for class ToolsAliasImportPostRequest.");

            writer.WriteString("table", toolsAliasImportPostRequest.Table);

            writer.WriteString("data", toolsAliasImportPostRequest.Data);

            var formatRawValue = ToolsAliasImportPostRequest.FormatEnumToJsonValue(toolsAliasImportPostRequest.FormatOption.Value!.Value);
            writer.WriteString("format", formatRawValue);
            if (toolsAliasImportPostRequest.TruncateOption.IsSet)
                writer.WriteBoolean("truncate", toolsAliasImportPostRequest.TruncateOption.Value!.Value);

            if (toolsAliasImportPostRequest.CreateIfMissingOption.IsSet)
                writer.WriteBoolean("create_if_missing", toolsAliasImportPostRequest.CreateIfMissingOption.Value!.Value);

            if (toolsAliasImportPostRequest.DatabaseOption.IsSet)
                writer.WriteString("database", toolsAliasImportPostRequest.Database);

            if (toolsAliasImportPostRequest.SchemaOption.IsSet)
                writer.WriteString("schema", toolsAliasImportPostRequest.Schema);
        }
    }
}
