/* tslint:disable */
/* eslint-disable */
/**
 * River REST API
 * Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 
 *
 * The version of the OpenAPI document: 0.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ArchiveEntry
 */
export interface ArchiveEntry {
    /**
     * 
     */
    name?: string;
    /**
     * 
     */
    sizeBytes?: number;
    /**
     * 
     */
    createdAt?: string;
}

/**
 * Check if a given object implements the ArchiveEntry interface.
 */
export function instanceOfArchiveEntry(value: object): value is ArchiveEntry {
    return true;
}

export function ArchiveEntryFromJSON(json: any): ArchiveEntry {
    return ArchiveEntryFromJSONTyped(json, false);
}

export function ArchiveEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArchiveEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'sizeBytes': json['size_bytes'] == null ? undefined : json['size_bytes'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
    };
}

export function ArchiveEntryToJSON(json: any): ArchiveEntry {
    return ArchiveEntryToJSONTyped(json, false);
}

export function ArchiveEntryToJSONTyped(value?: ArchiveEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'size_bytes': value['sizeBytes'],
        'created_at': value['createdAt'],
    };
}

