/* tslint:disable */
/* eslint-disable */
/**
 * River REST API
 * Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 
 *
 * The version of the OpenAPI document: 0.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthRegisterPostRequest
 */
export interface AuthRegisterPostRequest {
    /**
     * 
     */
    orgName: string;
    /**
     * 
     */
    email: string;
    /**
     * 
     */
    password: string;
}

/**
 * Check if a given object implements the AuthRegisterPostRequest interface.
 */
export function instanceOfAuthRegisterPostRequest(value: object): value is AuthRegisterPostRequest {
    if ((!('orgName' in (value as Record<string, any>)) && !('org_name' in (value as Record<string, any>))) || ((value as Record<string, any>)['orgName'] === undefined && (value as Record<string, any>)['org_name'] === undefined)) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function AuthRegisterPostRequestFromJSON(json: any): AuthRegisterPostRequest {
    return AuthRegisterPostRequestFromJSONTyped(json, false);
}

export function AuthRegisterPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthRegisterPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'orgName': json['org_name'],
        'email': json['email'],
        'password': json['password'],
    };
}

export function AuthRegisterPostRequestToJSON(json: any): AuthRegisterPostRequest {
    return AuthRegisterPostRequestToJSONTyped(json, false);
}

export function AuthRegisterPostRequestToJSONTyped(value?: AuthRegisterPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'org_name': value['orgName'],
        'email': value['email'],
        'password': value['password'],
    };
}

