/* tslint:disable */
/* eslint-disable */
/**
 * River REST API
 * Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BiDashboardsIdEmbedDelete200Response
 */
export interface BiDashboardsIdEmbedDelete200Response {
    /**
     * 
     */
    revoked?: string;
}

/**
 * Check if a given object implements the BiDashboardsIdEmbedDelete200Response interface.
 */
export function instanceOfBiDashboardsIdEmbedDelete200Response(value: object): value is BiDashboardsIdEmbedDelete200Response {
    return true;
}

export function BiDashboardsIdEmbedDelete200ResponseFromJSON(json: any): BiDashboardsIdEmbedDelete200Response {
    return BiDashboardsIdEmbedDelete200ResponseFromJSONTyped(json, false);
}

export function BiDashboardsIdEmbedDelete200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BiDashboardsIdEmbedDelete200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'revoked': json['revoked'] == null ? undefined : json['revoked'],
    };
}

export function BiDashboardsIdEmbedDelete200ResponseToJSON(json: any): BiDashboardsIdEmbedDelete200Response {
    return BiDashboardsIdEmbedDelete200ResponseToJSONTyped(json, false);
}

export function BiDashboardsIdEmbedDelete200ResponseToJSONTyped(value?: BiDashboardsIdEmbedDelete200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'revoked': value['revoked'],
    };
}

