/* tslint:disable */
/* eslint-disable */
/**
 * River REST API
 * Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 
 *
 * The version of the OpenAPI document: 0.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { BiFilter } from './BiFilter';
import {
    BiFilterFromJSON,
    BiFilterFromJSONTyped,
    BiFilterToJSON,
    BiFilterToJSONTyped,
} from './BiFilter';
import type { BiTile } from './BiTile';
import {
    BiTileFromJSON,
    BiTileFromJSONTyped,
    BiTileToJSON,
    BiTileToJSONTyped,
} from './BiTile';

/**
 * 
 * @export
 * @interface BiDashboard
 */
export interface BiDashboard {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    name: string;
    /**
     * present on single-dashboard reads only
     */
    tiles?: Array<BiTile>;
    /**
     * present on single-dashboard reads only
     */
    filters?: Array<BiFilter>;
    /**
     * M5 named color palette for the dashboard's charts (default river)
     */
    theme?: BiDashboardThemeEnum;
    /**
     * 
     */
    updatedAt: Date;
    /**
     * 
     */
    updatedBy?: string;
}


/**
 * @export
 */
export const BiDashboardThemeEnum = {
    River: 'river',
    Sunset: 'sunset',
    Forest: 'forest',
    Berry: 'berry',
    Mono: 'mono',
} as const;
export type BiDashboardThemeEnum = typeof BiDashboardThemeEnum[keyof typeof BiDashboardThemeEnum];


/**
 * Check if a given object implements the BiDashboard interface.
 */
export function instanceOfBiDashboard(value: object): value is BiDashboard {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if ((!('updatedAt' in (value as Record<string, any>)) && !('updated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['updatedAt'] === undefined && (value as Record<string, any>)['updated_at'] === undefined)) return false;
    return true;
}

export function BiDashboardFromJSON(json: any): BiDashboard {
    return BiDashboardFromJSONTyped(json, false);
}

export function BiDashboardFromJSONTyped(json: any, ignoreDiscriminator: boolean): BiDashboard {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'tiles': json['tiles'] == null ? undefined : ((json['tiles'] as Array<any>).map(BiTileFromJSON)),
        'filters': json['filters'] == null ? undefined : ((json['filters'] as Array<any>).map(BiFilterFromJSON)),
        'theme': json['theme'] == null ? undefined : json['theme'],
        'updatedAt': (json['updated_at'] == null ? json['updated_at'] : parseDateTime(json['updated_at'])),
        'updatedBy': json['updated_by'] == null ? undefined : json['updated_by'],
    };
}

export function BiDashboardToJSON(json: any): BiDashboard {
    return BiDashboardToJSONTyped(json, false);
}

export function BiDashboardToJSONTyped(value?: BiDashboard | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'tiles': value['tiles'] == null ? undefined : ((value['tiles'] as Array<any>).map(BiTileToJSON)),
        'filters': value['filters'] == null ? undefined : ((value['filters'] as Array<any>).map(BiFilterToJSON)),
        'theme': value['theme'],
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : serializeDateTime(value['updatedAt']),
        'updated_by': value['updatedBy'],
    };
}

