/* tslint:disable */
/* eslint-disable */
/**
 * River REST API
 * Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 
 *
 * The version of the OpenAPI document: 0.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BiDashboard } from './BiDashboard';
import {
    BiDashboardFromJSON,
    BiDashboardFromJSONTyped,
    BiDashboardToJSON,
    BiDashboardToJSONTyped,
} from './BiDashboard';

/**
 * 
 * @export
 * @interface BiDashboardsGet200Response
 */
export interface BiDashboardsGet200Response {
    /**
     * 
     */
    dashboards?: Array<BiDashboard>;
}

/**
 * Check if a given object implements the BiDashboardsGet200Response interface.
 */
export function instanceOfBiDashboardsGet200Response(value: object): value is BiDashboardsGet200Response {
    return true;
}

export function BiDashboardsGet200ResponseFromJSON(json: any): BiDashboardsGet200Response {
    return BiDashboardsGet200ResponseFromJSONTyped(json, false);
}

export function BiDashboardsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BiDashboardsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'dashboards': json['dashboards'] == null ? undefined : ((json['dashboards'] as Array<any>).map(BiDashboardFromJSON)),
    };
}

export function BiDashboardsGet200ResponseToJSON(json: any): BiDashboardsGet200Response {
    return BiDashboardsGet200ResponseToJSONTyped(json, false);
}

export function BiDashboardsGet200ResponseToJSONTyped(value?: BiDashboardsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dashboards': value['dashboards'] == null ? undefined : ((value['dashboards'] as Array<any>).map(BiDashboardToJSON)),
    };
}

