/* tslint:disable */
/* eslint-disable */
/**
 * River REST API
 * Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 
 *
 * The version of the OpenAPI document: 0.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BiFilter } from './BiFilter';
import {
    BiFilterFromJSON,
    BiFilterFromJSONTyped,
    BiFilterToJSON,
    BiFilterToJSONTyped,
} from './BiFilter';
import type { BiTile } from './BiTile';
import {
    BiTileFromJSON,
    BiTileFromJSONTyped,
    BiTileToJSON,
    BiTileToJSONTyped,
} from './BiTile';

/**
 * 
 * @export
 * @interface BiDashboardsIdPutRequest
 */
export interface BiDashboardsIdPutRequest {
    /**
     * 
     */
    name?: string;
    /**
     * 
     */
    tiles?: Array<BiTile>;
    /**
     * 
     */
    filters?: Array<BiFilter>;
}

/**
 * Check if a given object implements the BiDashboardsIdPutRequest interface.
 */
export function instanceOfBiDashboardsIdPutRequest(value: object): value is BiDashboardsIdPutRequest {
    return true;
}

export function BiDashboardsIdPutRequestFromJSON(json: any): BiDashboardsIdPutRequest {
    return BiDashboardsIdPutRequestFromJSONTyped(json, false);
}

export function BiDashboardsIdPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BiDashboardsIdPutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'tiles': json['tiles'] == null ? undefined : ((json['tiles'] as Array<any>).map(BiTileFromJSON)),
        'filters': json['filters'] == null ? undefined : ((json['filters'] as Array<any>).map(BiFilterFromJSON)),
    };
}

export function BiDashboardsIdPutRequestToJSON(json: any): BiDashboardsIdPutRequest {
    return BiDashboardsIdPutRequestToJSONTyped(json, false);
}

export function BiDashboardsIdPutRequestToJSONTyped(value?: BiDashboardsIdPutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'tiles': value['tiles'] == null ? undefined : ((value['tiles'] as Array<any>).map(BiTileToJSON)),
        'filters': value['filters'] == null ? undefined : ((value['filters'] as Array<any>).map(BiFilterToJSON)),
    };
}

