/* tslint:disable */
/* eslint-disable */
/**
 * River REST API
 * Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DesignerModelTablesInnerIndexesInner
 */
export interface DesignerModelTablesInnerIndexesInner {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    columns: Array<string>;
    /**
     * 
     */
    unique?: boolean;
}

/**
 * Check if a given object implements the DesignerModelTablesInnerIndexesInner interface.
 */
export function instanceOfDesignerModelTablesInnerIndexesInner(value: object): value is DesignerModelTablesInnerIndexesInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('columns' in value) || value['columns'] === undefined) return false;
    return true;
}

export function DesignerModelTablesInnerIndexesInnerFromJSON(json: any): DesignerModelTablesInnerIndexesInner {
    return DesignerModelTablesInnerIndexesInnerFromJSONTyped(json, false);
}

export function DesignerModelTablesInnerIndexesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): DesignerModelTablesInnerIndexesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'columns': json['columns'],
        'unique': json['unique'] == null ? undefined : json['unique'],
    };
}

export function DesignerModelTablesInnerIndexesInnerToJSON(json: any): DesignerModelTablesInnerIndexesInner {
    return DesignerModelTablesInnerIndexesInnerToJSONTyped(json, false);
}

export function DesignerModelTablesInnerIndexesInnerToJSONTyped(value?: DesignerModelTablesInnerIndexesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'columns': value['columns'],
        'unique': value['unique'],
    };
}

