/* tslint:disable */
/* eslint-disable */
/**
 * River REST API
 * Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 
 *
 * The version of the OpenAPI document: 0.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * diff-derived migration for one publish (per-statement apply results)
 * @export
 * @interface DesignerMigration
 */
export interface DesignerMigration {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    designId: string;
    /**
     * 
     */
    fromVersion?: number;
    /**
     * 
     */
    toVersion: number;
    /**
     * 
     */
    targetAlias?: string;
    /**
     * 
     */
    targetSchema?: string;
    /**
     * 
     */
    status: DesignerMigrationStatusEnum;
    /**
     * ordered DDL statements (id/op/sql/destructive/description)
     */
    statements: Array<object>;
    /**
     * per-statement apply results ({id, ok, error, duration_ms})
     */
    results?: Array<object>;
    /**
     * 
     */
    appliedBy?: string;
    /**
     * 
     */
    appliedAt?: string;
    /**
     * 
     */
    durationMs?: number;
    /**
     * 
     */
    error?: string;
}


/**
 * @export
 */
export const DesignerMigrationStatusEnum = {
    Pending: 'pending',
    Applied: 'applied',
    Failed: 'failed',
    Partial: 'partial',
} as const;
export type DesignerMigrationStatusEnum = typeof DesignerMigrationStatusEnum[keyof typeof DesignerMigrationStatusEnum];


/**
 * Check if a given object implements the DesignerMigration interface.
 */
export function instanceOfDesignerMigration(value: object): value is DesignerMigration {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('designId' in (value as Record<string, any>)) && !('design_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['designId'] === undefined && (value as Record<string, any>)['design_id'] === undefined)) return false;
    if ((!('toVersion' in (value as Record<string, any>)) && !('to_version' in (value as Record<string, any>))) || ((value as Record<string, any>)['toVersion'] === undefined && (value as Record<string, any>)['to_version'] === undefined)) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('statements' in value) || value['statements'] === undefined) return false;
    return true;
}

export function DesignerMigrationFromJSON(json: any): DesignerMigration {
    return DesignerMigrationFromJSONTyped(json, false);
}

export function DesignerMigrationFromJSONTyped(json: any, ignoreDiscriminator: boolean): DesignerMigration {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'designId': json['design_id'],
        'fromVersion': json['from_version'] == null ? undefined : json['from_version'],
        'toVersion': json['to_version'],
        'targetAlias': json['target_alias'] == null ? undefined : json['target_alias'],
        'targetSchema': json['target_schema'] == null ? undefined : json['target_schema'],
        'status': json['status'],
        'statements': json['statements'],
        'results': json['results'] == null ? undefined : json['results'],
        'appliedBy': json['applied_by'] == null ? undefined : json['applied_by'],
        'appliedAt': json['applied_at'] == null ? undefined : json['applied_at'],
        'durationMs': json['duration_ms'] == null ? undefined : json['duration_ms'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function DesignerMigrationToJSON(json: any): DesignerMigration {
    return DesignerMigrationToJSONTyped(json, false);
}

export function DesignerMigrationToJSONTyped(value?: DesignerMigration | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'design_id': value['designId'],
        'from_version': value['fromVersion'],
        'to_version': value['toVersion'],
        'target_alias': value['targetAlias'],
        'target_schema': value['targetSchema'],
        'status': value['status'],
        'statements': value['statements'],
        'results': value['results'],
        'applied_by': value['appliedBy'],
        'applied_at': value['appliedAt'],
        'duration_ms': value['durationMs'],
        'error': value['error'],
    };
}

