/* tslint:disable */
/* eslint-disable */
/**
 * River REST API
 * Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 
 *
 * The version of the OpenAPI document: 0.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotebooksIdCompletePostRequest
 */
export interface NotebooksIdCompletePostRequest {
    /**
     * 
     */
    code: string;
    /**
     * 
     */
    cursorPos: number;
}

/**
 * Check if a given object implements the NotebooksIdCompletePostRequest interface.
 */
export function instanceOfNotebooksIdCompletePostRequest(value: object): value is NotebooksIdCompletePostRequest {
    if (!('code' in value) || value['code'] === undefined) return false;
    if ((!('cursorPos' in (value as Record<string, any>)) && !('cursor_pos' in (value as Record<string, any>))) || ((value as Record<string, any>)['cursorPos'] === undefined && (value as Record<string, any>)['cursor_pos'] === undefined)) return false;
    return true;
}

export function NotebooksIdCompletePostRequestFromJSON(json: any): NotebooksIdCompletePostRequest {
    return NotebooksIdCompletePostRequestFromJSONTyped(json, false);
}

export function NotebooksIdCompletePostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotebooksIdCompletePostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'cursorPos': json['cursor_pos'],
    };
}

export function NotebooksIdCompletePostRequestToJSON(json: any): NotebooksIdCompletePostRequest {
    return NotebooksIdCompletePostRequestToJSONTyped(json, false);
}

export function NotebooksIdCompletePostRequestToJSONTyped(value?: NotebooksIdCompletePostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'cursor_pos': value['cursorPos'],
    };
}

