/* tslint:disable */
/* eslint-disable */
/**
 * River REST API
 * Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 
 *
 * The version of the OpenAPI document: 0.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * query-file tree node (folders are nodes with children)
 * @export
 * @interface QueryFileNode
 */
export interface QueryFileNode {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    parentId?: string;
    /**
     * 
     */
    updatedAt: Date;
    /**
     * 
     */
    children: Array<QueryFileNode>;
}

/**
 * Check if a given object implements the QueryFileNode interface.
 */
export function instanceOfQueryFileNode(value: object): value is QueryFileNode {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if ((!('updatedAt' in (value as Record<string, any>)) && !('updated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['updatedAt'] === undefined && (value as Record<string, any>)['updated_at'] === undefined)) return false;
    if (!('children' in value) || value['children'] === undefined) return false;
    return true;
}

export function QueryFileNodeFromJSON(json: any): QueryFileNode {
    return QueryFileNodeFromJSONTyped(json, false);
}

export function QueryFileNodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryFileNode {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'parentId': json['parent_id'] == null ? undefined : json['parent_id'],
        'updatedAt': (json['updated_at'] == null ? json['updated_at'] : parseDateTime(json['updated_at'])),
        'children': ((json['children'] as Array<any>).map(QueryFileNodeFromJSON)),
    };
}

export function QueryFileNodeToJSON(json: any): QueryFileNode {
    return QueryFileNodeToJSONTyped(json, false);
}

export function QueryFileNodeToJSONTyped(value?: QueryFileNode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'parent_id': value['parentId'],
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : serializeDateTime(value['updatedAt']),
        'children': ((value['children'] as Array<any>).map(QueryFileNodeToJSON)),
    };
}

