/* tslint:disable */
/* eslint-disable */
/**
 * River REST API
 * Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 
 *
 * The version of the OpenAPI document: 0.10.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QueryExplainPostRequest
 */
export interface QueryExplainPostRequest {
    /**
     * 
     */
    sql?: string;
    /**
     * 
     */
    ai?: boolean;
}

/**
 * Check if a given object implements the QueryExplainPostRequest interface.
 */
export function instanceOfQueryExplainPostRequest(value: object): value is QueryExplainPostRequest {
    return true;
}

export function QueryExplainPostRequestFromJSON(json: any): QueryExplainPostRequest {
    return QueryExplainPostRequestFromJSONTyped(json, false);
}

export function QueryExplainPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryExplainPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'sql': json['sql'] == null ? undefined : json['sql'],
        'ai': json['ai'] == null ? undefined : json['ai'],
    };
}

export function QueryExplainPostRequestToJSON(json: any): QueryExplainPostRequest {
    return QueryExplainPostRequestToJSONTyped(json, false);
}

export function QueryExplainPostRequestToJSONTyped(value?: QueryExplainPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sql': value['sql'],
        'ai': value['ai'],
    };
}

