/* tslint:disable */
/* eslint-disable */
/**
 * River REST API
 * Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TablesAliasRowsDeletePostRequest
 */
export interface TablesAliasRowsDeletePostRequest {
    /**
     * 
     */
    table: string;
    /**
     * 
     */
    database?: string;
    /**
     * 
     */
    schema?: string;
    /**
     * 
     */
    keys: Array<{ [key: string]: any | undefined; }>;
}

/**
 * Check if a given object implements the TablesAliasRowsDeletePostRequest interface.
 */
export function instanceOfTablesAliasRowsDeletePostRequest(value: object): value is TablesAliasRowsDeletePostRequest {
    if (!('table' in value) || value['table'] === undefined) return false;
    if (!('keys' in value) || value['keys'] === undefined) return false;
    return true;
}

export function TablesAliasRowsDeletePostRequestFromJSON(json: any): TablesAliasRowsDeletePostRequest {
    return TablesAliasRowsDeletePostRequestFromJSONTyped(json, false);
}

export function TablesAliasRowsDeletePostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TablesAliasRowsDeletePostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'table': json['table'],
        'database': json['database'] == null ? undefined : json['database'],
        'schema': json['schema'] == null ? undefined : json['schema'],
        'keys': json['keys'],
    };
}

export function TablesAliasRowsDeletePostRequestToJSON(json: any): TablesAliasRowsDeletePostRequest {
    return TablesAliasRowsDeletePostRequestToJSONTyped(json, false);
}

export function TablesAliasRowsDeletePostRequestToJSONTyped(value?: TablesAliasRowsDeletePostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'table': value['table'],
        'database': value['database'],
        'schema': value['schema'],
        'keys': value['keys'],
    };
}

