/* tslint:disable */
/* eslint-disable */
/**
 * River REST API
 * Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface WardenInstance
 */
export interface WardenInstance {
    /**
     * 
     */
    fqdn: string;
    /**
     * 
     */
    slug: string;
    /**
     * 
     */
    backend: WardenInstanceBackendEnum;
    /**
     * 
     */
    image: string;
    /**
     * 
     */
    containerId?: string;
    /**
     * 
     */
    hostPort: number;
    /**
     * 
     */
    volume: string;
    /**
     * identifier-safe connection alias (hyphens → underscores)
     */
    riverqlAlias: string;
    /**
     * 
     */
    createdBy: string;
    /**
     * 
     */
    createdAt: Date;
    /**
     * 
     */
    status: WardenInstanceStatusEnum;
    /**
     * 
     */
    lastError?: string;
    /**
     * 
     */
    endpointFqdn?: string;
    /**
     * 
     */
    endpointLocal?: string;
    /**
     * secret reference — plaintext never leaves the SecretStore
     */
    passwordRef?: string;
    /**
     * 
     */
    riverqlHealth?: string;
    /**
     * 
     */
    routePublished?: boolean;
}


/**
 * @export
 */
export const WardenInstanceBackendEnum = {
    Postgres: 'postgres',
    Mysql: 'mysql',
    Mongodb: 'mongodb',
} as const;
export type WardenInstanceBackendEnum = typeof WardenInstanceBackendEnum[keyof typeof WardenInstanceBackendEnum];

/**
 * @export
 */
export const WardenInstanceStatusEnum = {
    Provisioning: 'provisioning',
    Active: 'active',
    Degraded: 'degraded',
    Stopped: 'stopped',
    Lost: 'lost',
    Archived: 'archived',
    Failed: 'failed',
} as const;
export type WardenInstanceStatusEnum = typeof WardenInstanceStatusEnum[keyof typeof WardenInstanceStatusEnum];


/**
 * Check if a given object implements the WardenInstance interface.
 */
export function instanceOfWardenInstance(value: object): value is WardenInstance {
    if (!('fqdn' in value) || value['fqdn'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('backend' in value) || value['backend'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    if ((!('hostPort' in (value as Record<string, any>)) && !('host_port' in (value as Record<string, any>))) || ((value as Record<string, any>)['hostPort'] === undefined && (value as Record<string, any>)['host_port'] === undefined)) return false;
    if (!('volume' in value) || value['volume'] === undefined) return false;
    if ((!('riverqlAlias' in (value as Record<string, any>)) && !('riverql_alias' in (value as Record<string, any>))) || ((value as Record<string, any>)['riverqlAlias'] === undefined && (value as Record<string, any>)['riverql_alias'] === undefined)) return false;
    if ((!('createdBy' in (value as Record<string, any>)) && !('created_by' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdBy'] === undefined && (value as Record<string, any>)['created_by'] === undefined)) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function WardenInstanceFromJSON(json: any): WardenInstance {
    return WardenInstanceFromJSONTyped(json, false);
}

export function WardenInstanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): WardenInstance {
    if (json == null) {
        return json;
    }
    return {
        
        'fqdn': json['fqdn'],
        'slug': json['slug'],
        'backend': json['backend'],
        'image': json['image'],
        'containerId': json['container_id'] == null ? undefined : json['container_id'],
        'hostPort': json['host_port'],
        'volume': json['volume'],
        'riverqlAlias': json['riverql_alias'],
        'createdBy': json['created_by'],
        'createdAt': (json['created_at'] == null ? json['created_at'] : parseDateTime(json['created_at'])),
        'status': json['status'],
        'lastError': json['last_error'] == null ? undefined : json['last_error'],
        'endpointFqdn': json['endpoint_fqdn'] == null ? undefined : json['endpoint_fqdn'],
        'endpointLocal': json['endpoint_local'] == null ? undefined : json['endpoint_local'],
        'passwordRef': json['password_ref'] == null ? undefined : json['password_ref'],
        'riverqlHealth': json['riverql_health'] == null ? undefined : json['riverql_health'],
        'routePublished': json['route_published'] == null ? undefined : json['route_published'],
    };
}

export function WardenInstanceToJSON(json: any): WardenInstance {
    return WardenInstanceToJSONTyped(json, false);
}

export function WardenInstanceToJSONTyped(value?: WardenInstance | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fqdn': value['fqdn'],
        'slug': value['slug'],
        'backend': value['backend'],
        'image': value['image'],
        'container_id': value['containerId'],
        'host_port': value['hostPort'],
        'volume': value['volume'],
        'riverql_alias': value['riverqlAlias'],
        'created_by': value['createdBy'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'status': value['status'],
        'last_error': value['lastError'],
        'endpoint_fqdn': value['endpointFqdn'],
        'endpoint_local': value['endpointLocal'],
        'password_ref': value['passwordRef'],
        'riverql_health': value['riverqlHealth'],
        'route_published': value['routePublished'],
    };
}

