/*
 * River REST API
 *
 * Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiLilyPost200Response {
    #[serde(rename = "reply", skip_serializing_if = "Option::is_none")]
    pub reply: Option<String>,
    #[serde(rename = "sql", skip_serializing_if = "Option::is_none")]
    pub sql: Option<String>,
    /// Validated action objects — open/insert_sql/run_sql/ create_query_file/create_notebook/add_notebook_cell/ create_design/add_design_tables/update_design_table/ delete_design_table/update_design_indexes/ update_design_relationship/delete_design_relationship/ set_design_target/rename_design/delete_design/ restore_design_version/publish_design/apply_migration/ create_dashboard/add_dashboard_tile/update_dashboard_tile/ delete_dashboard_tile/set_dashboard_filters/ create_embed_link/create_bucket/create_fs_folder/ delete_fs_node/provision_database/attach_database/ restart_database/destroy_database/connect_database — applied by the client only after user confirmation. 
    #[serde(rename = "actions", skip_serializing_if = "Option::is_none")]
    pub actions: Option<Vec<serde_json::Value>>,
}

impl AiLilyPost200Response {
    pub fn new() -> AiLilyPost200Response {
        AiLilyPost200Response {
            reply: None,
            sql: None,
            actions: None,
        }
    }
}

