/*
 * River REST API
 *
 * Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BiDashboardsIdSnapshotPost200Response {
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// number of tile entries stored
    #[serde(rename = "tiles", skip_serializing_if = "Option::is_none")]
    pub tiles: Option<i32>,
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<i32>,
}

impl BiDashboardsIdSnapshotPost200Response {
    pub fn new() -> BiDashboardsIdSnapshotPost200Response {
        BiDashboardsIdSnapshotPost200Response {
            created_at: None,
            tiles: None,
            errors: None,
        }
    }
}

