/*
 * River REST API
 *
 * Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 
 *
 * The version of the OpenAPI document: 0.10.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BiFilter : M3 dashboard filter declaration. `param` names the `:param` token tile queries bind to; daterange filters bind `<param>_from` / `<param>_to` (ISO dates). Values live on the client; this is the authoring contract. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BiFilter {
    #[serde(rename = "id")]
    pub id: String,
    /// identifier bound to tile :param tokens
    #[serde(rename = "param")]
    pub param: String,
    #[serde(rename = "kind")]
    pub kind: Kind,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// category choices (declared by the author; cross-filter writes these too)
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<Vec<String>>,
    /// category default (used by the background warmer)
    #[serde(rename = "default", skip_serializing_if = "Option::is_none")]
    pub default: Option<String>,
}

impl BiFilter {
    /// M3 dashboard filter declaration. `param` names the `:param` token tile queries bind to; daterange filters bind `<param>_from` / `<param>_to` (ISO dates). Values live on the client; this is the authoring contract. 
    pub fn new(id: String, param: String, kind: Kind) -> BiFilter {
        BiFilter {
            id,
            param,
            kind,
            label: None,
            options: None,
            default: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "category")]
    Category,
    #[serde(rename = "daterange")]
    Daterange,
}

impl Default for Kind {
    fn default() -> Kind {
        Self::Category
    }
}

