/*
River REST API

Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 

API version: 0.10.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rivergo

import (
	"encoding/json"
)

// checks if the AiConversationsPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AiConversationsPostRequest{}

// AiConversationsPostRequest struct for AiConversationsPostRequest
type AiConversationsPostRequest struct {
	Title *string `json:"title,omitempty"`
	Messages []AiConversationsPostRequestMessagesInner `json:"messages,omitempty"`
}

// NewAiConversationsPostRequest instantiates a new AiConversationsPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAiConversationsPostRequest() *AiConversationsPostRequest {
	this := AiConversationsPostRequest{}
	return &this
}

// NewAiConversationsPostRequestWithDefaults instantiates a new AiConversationsPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAiConversationsPostRequestWithDefaults() *AiConversationsPostRequest {
	this := AiConversationsPostRequest{}
	return &this
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *AiConversationsPostRequest) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiConversationsPostRequest) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *AiConversationsPostRequest) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *AiConversationsPostRequest) SetTitle(v string) {
	o.Title = &v
}

// GetMessages returns the Messages field value if set, zero value otherwise.
func (o *AiConversationsPostRequest) GetMessages() []AiConversationsPostRequestMessagesInner {
	if o == nil || IsNil(o.Messages) {
		var ret []AiConversationsPostRequestMessagesInner
		return ret
	}
	return o.Messages
}

// GetMessagesOk returns a tuple with the Messages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiConversationsPostRequest) GetMessagesOk() ([]AiConversationsPostRequestMessagesInner, bool) {
	if o == nil || IsNil(o.Messages) {
		return nil, false
	}
	return o.Messages, true
}

// HasMessages returns a boolean if a field has been set.
func (o *AiConversationsPostRequest) HasMessages() bool {
	if o != nil && !IsNil(o.Messages) {
		return true
	}

	return false
}

// SetMessages gets a reference to the given []AiConversationsPostRequestMessagesInner and assigns it to the Messages field.
func (o *AiConversationsPostRequest) SetMessages(v []AiConversationsPostRequestMessagesInner) {
	o.Messages = v
}

func (o AiConversationsPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AiConversationsPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Messages) {
		toSerialize["messages"] = o.Messages
	}
	return toSerialize, nil
}

type NullableAiConversationsPostRequest struct {
	value *AiConversationsPostRequest
	isSet bool
}

func (v NullableAiConversationsPostRequest) Get() *AiConversationsPostRequest {
	return v.value
}

func (v *NullableAiConversationsPostRequest) Set(val *AiConversationsPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAiConversationsPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAiConversationsPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAiConversationsPostRequest(val *AiConversationsPostRequest) *NullableAiConversationsPostRequest {
	return &NullableAiConversationsPostRequest{value: val, isSet: true}
}

func (v NullableAiConversationsPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAiConversationsPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


