/*
River REST API

Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 

API version: 0.10.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rivergo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NotebooksIdExecutePostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NotebooksIdExecutePostRequest{}

// NotebooksIdExecutePostRequest struct for NotebooksIdExecutePostRequest
type NotebooksIdExecutePostRequest struct {
	CellId string `json:"cell_id"`
	// override the stored cell source
	Code *string `json:"code,omitempty"`
}

type _NotebooksIdExecutePostRequest NotebooksIdExecutePostRequest

// NewNotebooksIdExecutePostRequest instantiates a new NotebooksIdExecutePostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNotebooksIdExecutePostRequest(cellId string) *NotebooksIdExecutePostRequest {
	this := NotebooksIdExecutePostRequest{}
	this.CellId = cellId
	return &this
}

// NewNotebooksIdExecutePostRequestWithDefaults instantiates a new NotebooksIdExecutePostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNotebooksIdExecutePostRequestWithDefaults() *NotebooksIdExecutePostRequest {
	this := NotebooksIdExecutePostRequest{}
	return &this
}

// GetCellId returns the CellId field value
func (o *NotebooksIdExecutePostRequest) GetCellId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CellId
}

// GetCellIdOk returns a tuple with the CellId field value
// and a boolean to check if the value has been set.
func (o *NotebooksIdExecutePostRequest) GetCellIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CellId, true
}

// SetCellId sets field value
func (o *NotebooksIdExecutePostRequest) SetCellId(v string) {
	o.CellId = v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *NotebooksIdExecutePostRequest) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotebooksIdExecutePostRequest) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *NotebooksIdExecutePostRequest) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *NotebooksIdExecutePostRequest) SetCode(v string) {
	o.Code = &v
}

func (o NotebooksIdExecutePostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NotebooksIdExecutePostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cell_id"] = o.CellId
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	return toSerialize, nil
}

func (o *NotebooksIdExecutePostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cell_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNotebooksIdExecutePostRequest := _NotebooksIdExecutePostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNotebooksIdExecutePostRequest)

	if err != nil {
		return err
	}

	*o = NotebooksIdExecutePostRequest(varNotebooksIdExecutePostRequest)

	return err
}

type NullableNotebooksIdExecutePostRequest struct {
	value *NotebooksIdExecutePostRequest
	isSet bool
}

func (v NullableNotebooksIdExecutePostRequest) Get() *NotebooksIdExecutePostRequest {
	return v.value
}

func (v *NullableNotebooksIdExecutePostRequest) Set(val *NotebooksIdExecutePostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableNotebooksIdExecutePostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableNotebooksIdExecutePostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotebooksIdExecutePostRequest(val *NotebooksIdExecutePostRequest) *NullableNotebooksIdExecutePostRequest {
	return &NullableNotebooksIdExecutePostRequest{value: val, isSet: true}
}

func (v NullableNotebooksIdExecutePostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotebooksIdExecutePostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


