/*
River REST API

Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 

API version: 0.9.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rivergo

import (
	"encoding/json"
)

// checks if the AuthUsersIdPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthUsersIdPatchRequest{}

// AuthUsersIdPatchRequest struct for AuthUsersIdPatchRequest
type AuthUsersIdPatchRequest struct {
	Role *string `json:"role,omitempty"`
	// full replacement list
	Permissions []string `json:"permissions,omitempty"`
}

// NewAuthUsersIdPatchRequest instantiates a new AuthUsersIdPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthUsersIdPatchRequest() *AuthUsersIdPatchRequest {
	this := AuthUsersIdPatchRequest{}
	return &this
}

// NewAuthUsersIdPatchRequestWithDefaults instantiates a new AuthUsersIdPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthUsersIdPatchRequestWithDefaults() *AuthUsersIdPatchRequest {
	this := AuthUsersIdPatchRequest{}
	return &this
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *AuthUsersIdPatchRequest) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthUsersIdPatchRequest) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *AuthUsersIdPatchRequest) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *AuthUsersIdPatchRequest) SetRole(v string) {
	o.Role = &v
}

// GetPermissions returns the Permissions field value if set, zero value otherwise.
func (o *AuthUsersIdPatchRequest) GetPermissions() []string {
	if o == nil || IsNil(o.Permissions) {
		var ret []string
		return ret
	}
	return o.Permissions
}

// GetPermissionsOk returns a tuple with the Permissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthUsersIdPatchRequest) GetPermissionsOk() ([]string, bool) {
	if o == nil || IsNil(o.Permissions) {
		return nil, false
	}
	return o.Permissions, true
}

// HasPermissions returns a boolean if a field has been set.
func (o *AuthUsersIdPatchRequest) HasPermissions() bool {
	if o != nil && !IsNil(o.Permissions) {
		return true
	}

	return false
}

// SetPermissions gets a reference to the given []string and assigns it to the Permissions field.
func (o *AuthUsersIdPatchRequest) SetPermissions(v []string) {
	o.Permissions = v
}

func (o AuthUsersIdPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthUsersIdPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	if !IsNil(o.Permissions) {
		toSerialize["permissions"] = o.Permissions
	}
	return toSerialize, nil
}

type NullableAuthUsersIdPatchRequest struct {
	value *AuthUsersIdPatchRequest
	isSet bool
}

func (v NullableAuthUsersIdPatchRequest) Get() *AuthUsersIdPatchRequest {
	return v.value
}

func (v *NullableAuthUsersIdPatchRequest) Set(val *AuthUsersIdPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthUsersIdPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthUsersIdPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthUsersIdPatchRequest(val *AuthUsersIdPatchRequest) *NullableAuthUsersIdPatchRequest {
	return &NullableAuthUsersIdPatchRequest{value: val, isSet: true}
}

func (v NullableAuthUsersIdPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthUsersIdPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


