/*
River REST API

Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 

API version: 0.10.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rivergo

import (
	"encoding/json"
)

// checks if the BiDashboardsIdDelete200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BiDashboardsIdDelete200Response{}

// BiDashboardsIdDelete200Response struct for BiDashboardsIdDelete200Response
type BiDashboardsIdDelete200Response struct {
	Removed *string `json:"removed,omitempty"`
}

// NewBiDashboardsIdDelete200Response instantiates a new BiDashboardsIdDelete200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBiDashboardsIdDelete200Response() *BiDashboardsIdDelete200Response {
	this := BiDashboardsIdDelete200Response{}
	return &this
}

// NewBiDashboardsIdDelete200ResponseWithDefaults instantiates a new BiDashboardsIdDelete200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBiDashboardsIdDelete200ResponseWithDefaults() *BiDashboardsIdDelete200Response {
	this := BiDashboardsIdDelete200Response{}
	return &this
}

// GetRemoved returns the Removed field value if set, zero value otherwise.
func (o *BiDashboardsIdDelete200Response) GetRemoved() string {
	if o == nil || IsNil(o.Removed) {
		var ret string
		return ret
	}
	return *o.Removed
}

// GetRemovedOk returns a tuple with the Removed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BiDashboardsIdDelete200Response) GetRemovedOk() (*string, bool) {
	if o == nil || IsNil(o.Removed) {
		return nil, false
	}
	return o.Removed, true
}

// HasRemoved returns a boolean if a field has been set.
func (o *BiDashboardsIdDelete200Response) HasRemoved() bool {
	if o != nil && !IsNil(o.Removed) {
		return true
	}

	return false
}

// SetRemoved gets a reference to the given string and assigns it to the Removed field.
func (o *BiDashboardsIdDelete200Response) SetRemoved(v string) {
	o.Removed = &v
}

func (o BiDashboardsIdDelete200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BiDashboardsIdDelete200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Removed) {
		toSerialize["removed"] = o.Removed
	}
	return toSerialize, nil
}

type NullableBiDashboardsIdDelete200Response struct {
	value *BiDashboardsIdDelete200Response
	isSet bool
}

func (v NullableBiDashboardsIdDelete200Response) Get() *BiDashboardsIdDelete200Response {
	return v.value
}

func (v *NullableBiDashboardsIdDelete200Response) Set(val *BiDashboardsIdDelete200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableBiDashboardsIdDelete200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableBiDashboardsIdDelete200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBiDashboardsIdDelete200Response(val *BiDashboardsIdDelete200Response) *NullableBiDashboardsIdDelete200Response {
	return &NullableBiDashboardsIdDelete200Response{value: val, isSet: true}
}

func (v NullableBiDashboardsIdDelete200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBiDashboardsIdDelete200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


