/*
River REST API

Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 

API version: 0.10.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rivergo

import (
	"encoding/json"
)

// checks if the AiBiTilePost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AiBiTilePost200Response{}

// AiBiTilePost200Response struct for AiBiTilePost200Response
type AiBiTilePost200Response struct {
	Tile *BiTile `json:"tile,omitempty"`
	Valid *bool `json:"valid,omitempty"`
	Error *string `json:"error,omitempty"`
	// raw model reply
	Raw *string `json:"raw,omitempty"`
}

// NewAiBiTilePost200Response instantiates a new AiBiTilePost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAiBiTilePost200Response() *AiBiTilePost200Response {
	this := AiBiTilePost200Response{}
	return &this
}

// NewAiBiTilePost200ResponseWithDefaults instantiates a new AiBiTilePost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAiBiTilePost200ResponseWithDefaults() *AiBiTilePost200Response {
	this := AiBiTilePost200Response{}
	return &this
}

// GetTile returns the Tile field value if set, zero value otherwise.
func (o *AiBiTilePost200Response) GetTile() BiTile {
	if o == nil || IsNil(o.Tile) {
		var ret BiTile
		return ret
	}
	return *o.Tile
}

// GetTileOk returns a tuple with the Tile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiBiTilePost200Response) GetTileOk() (*BiTile, bool) {
	if o == nil || IsNil(o.Tile) {
		return nil, false
	}
	return o.Tile, true
}

// HasTile returns a boolean if a field has been set.
func (o *AiBiTilePost200Response) HasTile() bool {
	if o != nil && !IsNil(o.Tile) {
		return true
	}

	return false
}

// SetTile gets a reference to the given BiTile and assigns it to the Tile field.
func (o *AiBiTilePost200Response) SetTile(v BiTile) {
	o.Tile = &v
}

// GetValid returns the Valid field value if set, zero value otherwise.
func (o *AiBiTilePost200Response) GetValid() bool {
	if o == nil || IsNil(o.Valid) {
		var ret bool
		return ret
	}
	return *o.Valid
}

// GetValidOk returns a tuple with the Valid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiBiTilePost200Response) GetValidOk() (*bool, bool) {
	if o == nil || IsNil(o.Valid) {
		return nil, false
	}
	return o.Valid, true
}

// HasValid returns a boolean if a field has been set.
func (o *AiBiTilePost200Response) HasValid() bool {
	if o != nil && !IsNil(o.Valid) {
		return true
	}

	return false
}

// SetValid gets a reference to the given bool and assigns it to the Valid field.
func (o *AiBiTilePost200Response) SetValid(v bool) {
	o.Valid = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *AiBiTilePost200Response) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiBiTilePost200Response) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *AiBiTilePost200Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *AiBiTilePost200Response) SetError(v string) {
	o.Error = &v
}

// GetRaw returns the Raw field value if set, zero value otherwise.
func (o *AiBiTilePost200Response) GetRaw() string {
	if o == nil || IsNil(o.Raw) {
		var ret string
		return ret
	}
	return *o.Raw
}

// GetRawOk returns a tuple with the Raw field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiBiTilePost200Response) GetRawOk() (*string, bool) {
	if o == nil || IsNil(o.Raw) {
		return nil, false
	}
	return o.Raw, true
}

// HasRaw returns a boolean if a field has been set.
func (o *AiBiTilePost200Response) HasRaw() bool {
	if o != nil && !IsNil(o.Raw) {
		return true
	}

	return false
}

// SetRaw gets a reference to the given string and assigns it to the Raw field.
func (o *AiBiTilePost200Response) SetRaw(v string) {
	o.Raw = &v
}

func (o AiBiTilePost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AiBiTilePost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Tile) {
		toSerialize["tile"] = o.Tile
	}
	if !IsNil(o.Valid) {
		toSerialize["valid"] = o.Valid
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.Raw) {
		toSerialize["raw"] = o.Raw
	}
	return toSerialize, nil
}

type NullableAiBiTilePost200Response struct {
	value *AiBiTilePost200Response
	isSet bool
}

func (v NullableAiBiTilePost200Response) Get() *AiBiTilePost200Response {
	return v.value
}

func (v *NullableAiBiTilePost200Response) Set(val *AiBiTilePost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableAiBiTilePost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableAiBiTilePost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAiBiTilePost200Response(val *AiBiTilePost200Response) *NullableAiBiTilePost200Response {
	return &NullableAiBiTilePost200Response{value: val, isSet: true}
}

func (v NullableAiBiTilePost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAiBiTilePost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


