/*
River REST API

Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 

API version: 0.9.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rivergo

import (
	"encoding/json"
)

// checks if the ImportReport type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImportReport{}

// ImportReport struct for ImportReport
type ImportReport struct {
	Table *string `json:"table,omitempty"`
	CreatedTable *bool `json:"created_table,omitempty"`
	Truncated *bool `json:"truncated,omitempty"`
	RowsRead *int32 `json:"rows_read,omitempty"`
	RowsInserted *int32 `json:"rows_inserted,omitempty"`
}

// NewImportReport instantiates a new ImportReport object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImportReport() *ImportReport {
	this := ImportReport{}
	return &this
}

// NewImportReportWithDefaults instantiates a new ImportReport object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImportReportWithDefaults() *ImportReport {
	this := ImportReport{}
	return &this
}

// GetTable returns the Table field value if set, zero value otherwise.
func (o *ImportReport) GetTable() string {
	if o == nil || IsNil(o.Table) {
		var ret string
		return ret
	}
	return *o.Table
}

// GetTableOk returns a tuple with the Table field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportReport) GetTableOk() (*string, bool) {
	if o == nil || IsNil(o.Table) {
		return nil, false
	}
	return o.Table, true
}

// HasTable returns a boolean if a field has been set.
func (o *ImportReport) HasTable() bool {
	if o != nil && !IsNil(o.Table) {
		return true
	}

	return false
}

// SetTable gets a reference to the given string and assigns it to the Table field.
func (o *ImportReport) SetTable(v string) {
	o.Table = &v
}

// GetCreatedTable returns the CreatedTable field value if set, zero value otherwise.
func (o *ImportReport) GetCreatedTable() bool {
	if o == nil || IsNil(o.CreatedTable) {
		var ret bool
		return ret
	}
	return *o.CreatedTable
}

// GetCreatedTableOk returns a tuple with the CreatedTable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportReport) GetCreatedTableOk() (*bool, bool) {
	if o == nil || IsNil(o.CreatedTable) {
		return nil, false
	}
	return o.CreatedTable, true
}

// HasCreatedTable returns a boolean if a field has been set.
func (o *ImportReport) HasCreatedTable() bool {
	if o != nil && !IsNil(o.CreatedTable) {
		return true
	}

	return false
}

// SetCreatedTable gets a reference to the given bool and assigns it to the CreatedTable field.
func (o *ImportReport) SetCreatedTable(v bool) {
	o.CreatedTable = &v
}

// GetTruncated returns the Truncated field value if set, zero value otherwise.
func (o *ImportReport) GetTruncated() bool {
	if o == nil || IsNil(o.Truncated) {
		var ret bool
		return ret
	}
	return *o.Truncated
}

// GetTruncatedOk returns a tuple with the Truncated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportReport) GetTruncatedOk() (*bool, bool) {
	if o == nil || IsNil(o.Truncated) {
		return nil, false
	}
	return o.Truncated, true
}

// HasTruncated returns a boolean if a field has been set.
func (o *ImportReport) HasTruncated() bool {
	if o != nil && !IsNil(o.Truncated) {
		return true
	}

	return false
}

// SetTruncated gets a reference to the given bool and assigns it to the Truncated field.
func (o *ImportReport) SetTruncated(v bool) {
	o.Truncated = &v
}

// GetRowsRead returns the RowsRead field value if set, zero value otherwise.
func (o *ImportReport) GetRowsRead() int32 {
	if o == nil || IsNil(o.RowsRead) {
		var ret int32
		return ret
	}
	return *o.RowsRead
}

// GetRowsReadOk returns a tuple with the RowsRead field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportReport) GetRowsReadOk() (*int32, bool) {
	if o == nil || IsNil(o.RowsRead) {
		return nil, false
	}
	return o.RowsRead, true
}

// HasRowsRead returns a boolean if a field has been set.
func (o *ImportReport) HasRowsRead() bool {
	if o != nil && !IsNil(o.RowsRead) {
		return true
	}

	return false
}

// SetRowsRead gets a reference to the given int32 and assigns it to the RowsRead field.
func (o *ImportReport) SetRowsRead(v int32) {
	o.RowsRead = &v
}

// GetRowsInserted returns the RowsInserted field value if set, zero value otherwise.
func (o *ImportReport) GetRowsInserted() int32 {
	if o == nil || IsNil(o.RowsInserted) {
		var ret int32
		return ret
	}
	return *o.RowsInserted
}

// GetRowsInsertedOk returns a tuple with the RowsInserted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportReport) GetRowsInsertedOk() (*int32, bool) {
	if o == nil || IsNil(o.RowsInserted) {
		return nil, false
	}
	return o.RowsInserted, true
}

// HasRowsInserted returns a boolean if a field has been set.
func (o *ImportReport) HasRowsInserted() bool {
	if o != nil && !IsNil(o.RowsInserted) {
		return true
	}

	return false
}

// SetRowsInserted gets a reference to the given int32 and assigns it to the RowsInserted field.
func (o *ImportReport) SetRowsInserted(v int32) {
	o.RowsInserted = &v
}

func (o ImportReport) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImportReport) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Table) {
		toSerialize["table"] = o.Table
	}
	if !IsNil(o.CreatedTable) {
		toSerialize["created_table"] = o.CreatedTable
	}
	if !IsNil(o.Truncated) {
		toSerialize["truncated"] = o.Truncated
	}
	if !IsNil(o.RowsRead) {
		toSerialize["rows_read"] = o.RowsRead
	}
	if !IsNil(o.RowsInserted) {
		toSerialize["rows_inserted"] = o.RowsInserted
	}
	return toSerialize, nil
}

type NullableImportReport struct {
	value *ImportReport
	isSet bool
}

func (v NullableImportReport) Get() *ImportReport {
	return v.value
}

func (v *NullableImportReport) Set(val *ImportReport) {
	v.value = val
	v.isSet = true
}

func (v NullableImportReport) IsSet() bool {
	return v.isSet
}

func (v *NullableImportReport) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImportReport(val *ImportReport) *NullableImportReport {
	return &NullableImportReport{value: val, isSet: true}
}

func (v NullableImportReport) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImportReport) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


