/*
River REST API

Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 

API version: 0.9.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rivergo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DesignerModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DesignerModel{}

// DesignerModel ERD model; stable ids (tbl_/col_/idx_/rel_) drive rename-aware diffs
type DesignerModel struct {
	Format *int32 `json:"format,omitempty"`
	Tables []DesignerModelTablesInner `json:"tables"`
	Relationships []DesignerModelRelationshipsInner `json:"relationships"`
}

type _DesignerModel DesignerModel

// NewDesignerModel instantiates a new DesignerModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDesignerModel(tables []DesignerModelTablesInner, relationships []DesignerModelRelationshipsInner) *DesignerModel {
	this := DesignerModel{}
	this.Tables = tables
	this.Relationships = relationships
	return &this
}

// NewDesignerModelWithDefaults instantiates a new DesignerModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDesignerModelWithDefaults() *DesignerModel {
	this := DesignerModel{}
	return &this
}

// GetFormat returns the Format field value if set, zero value otherwise.
func (o *DesignerModel) GetFormat() int32 {
	if o == nil || IsNil(o.Format) {
		var ret int32
		return ret
	}
	return *o.Format
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DesignerModel) GetFormatOk() (*int32, bool) {
	if o == nil || IsNil(o.Format) {
		return nil, false
	}
	return o.Format, true
}

// HasFormat returns a boolean if a field has been set.
func (o *DesignerModel) HasFormat() bool {
	if o != nil && !IsNil(o.Format) {
		return true
	}

	return false
}

// SetFormat gets a reference to the given int32 and assigns it to the Format field.
func (o *DesignerModel) SetFormat(v int32) {
	o.Format = &v
}

// GetTables returns the Tables field value
func (o *DesignerModel) GetTables() []DesignerModelTablesInner {
	if o == nil {
		var ret []DesignerModelTablesInner
		return ret
	}

	return o.Tables
}

// GetTablesOk returns a tuple with the Tables field value
// and a boolean to check if the value has been set.
func (o *DesignerModel) GetTablesOk() ([]DesignerModelTablesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tables, true
}

// SetTables sets field value
func (o *DesignerModel) SetTables(v []DesignerModelTablesInner) {
	o.Tables = v
}

// GetRelationships returns the Relationships field value
func (o *DesignerModel) GetRelationships() []DesignerModelRelationshipsInner {
	if o == nil {
		var ret []DesignerModelRelationshipsInner
		return ret
	}

	return o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value
// and a boolean to check if the value has been set.
func (o *DesignerModel) GetRelationshipsOk() ([]DesignerModelRelationshipsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Relationships, true
}

// SetRelationships sets field value
func (o *DesignerModel) SetRelationships(v []DesignerModelRelationshipsInner) {
	o.Relationships = v
}

func (o DesignerModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DesignerModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Format) {
		toSerialize["format"] = o.Format
	}
	toSerialize["tables"] = o.Tables
	toSerialize["relationships"] = o.Relationships
	return toSerialize, nil
}

func (o *DesignerModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tables",
		"relationships",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDesignerModel := _DesignerModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDesignerModel)

	if err != nil {
		return err
	}

	*o = DesignerModel(varDesignerModel)

	return err
}

type NullableDesignerModel struct {
	value *DesignerModel
	isSet bool
}

func (v NullableDesignerModel) Get() *DesignerModel {
	return v.value
}

func (v *NullableDesignerModel) Set(val *DesignerModel) {
	v.value = val
	v.isSet = true
}

func (v NullableDesignerModel) IsSet() bool {
	return v.isSet
}

func (v *NullableDesignerModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDesignerModel(val *DesignerModel) *NullableDesignerModel {
	return &NullableDesignerModel{value: val, isSet: true}
}

func (v NullableDesignerModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDesignerModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


