/*
River REST API

Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 

API version: 0.9.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rivergo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the QueryScriptPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueryScriptPostRequest{}

// QueryScriptPostRequest struct for QueryScriptPostRequest
type QueryScriptPostRequest struct {
	// Multi-statement SQL separated by ';'. The REST surface is AUTOCOMMIT — BEGIN/COMMIT/ROLLBACK are rejected (use the CLI exec --script / exec-file for transactions). 
	Script string `json:"script"`
}

type _QueryScriptPostRequest QueryScriptPostRequest

// NewQueryScriptPostRequest instantiates a new QueryScriptPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryScriptPostRequest(script string) *QueryScriptPostRequest {
	this := QueryScriptPostRequest{}
	this.Script = script
	return &this
}

// NewQueryScriptPostRequestWithDefaults instantiates a new QueryScriptPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryScriptPostRequestWithDefaults() *QueryScriptPostRequest {
	this := QueryScriptPostRequest{}
	return &this
}

// GetScript returns the Script field value
func (o *QueryScriptPostRequest) GetScript() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Script
}

// GetScriptOk returns a tuple with the Script field value
// and a boolean to check if the value has been set.
func (o *QueryScriptPostRequest) GetScriptOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Script, true
}

// SetScript sets field value
func (o *QueryScriptPostRequest) SetScript(v string) {
	o.Script = v
}

func (o QueryScriptPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueryScriptPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["script"] = o.Script
	return toSerialize, nil
}

func (o *QueryScriptPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"script",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQueryScriptPostRequest := _QueryScriptPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQueryScriptPostRequest)

	if err != nil {
		return err
	}

	*o = QueryScriptPostRequest(varQueryScriptPostRequest)

	return err
}

type NullableQueryScriptPostRequest struct {
	value *QueryScriptPostRequest
	isSet bool
}

func (v NullableQueryScriptPostRequest) Get() *QueryScriptPostRequest {
	return v.value
}

func (v *NullableQueryScriptPostRequest) Set(val *QueryScriptPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryScriptPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryScriptPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryScriptPostRequest(val *QueryScriptPostRequest) *NullableQueryScriptPostRequest {
	return &NullableQueryScriptPostRequest{value: val, isSet: true}
}

func (v NullableQueryScriptPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryScriptPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


