/*
River REST API

Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 

API version: 0.10.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rivergo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TablesAliasRowsQueryPostRequestSortInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TablesAliasRowsQueryPostRequestSortInner{}

// TablesAliasRowsQueryPostRequestSortInner struct for TablesAliasRowsQueryPostRequestSortInner
type TablesAliasRowsQueryPostRequestSortInner struct {
	Column string `json:"column"`
	Dir *string `json:"dir,omitempty"`
}

type _TablesAliasRowsQueryPostRequestSortInner TablesAliasRowsQueryPostRequestSortInner

// NewTablesAliasRowsQueryPostRequestSortInner instantiates a new TablesAliasRowsQueryPostRequestSortInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTablesAliasRowsQueryPostRequestSortInner(column string) *TablesAliasRowsQueryPostRequestSortInner {
	this := TablesAliasRowsQueryPostRequestSortInner{}
	this.Column = column
	var dir string = "asc"
	this.Dir = &dir
	return &this
}

// NewTablesAliasRowsQueryPostRequestSortInnerWithDefaults instantiates a new TablesAliasRowsQueryPostRequestSortInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTablesAliasRowsQueryPostRequestSortInnerWithDefaults() *TablesAliasRowsQueryPostRequestSortInner {
	this := TablesAliasRowsQueryPostRequestSortInner{}
	var dir string = "asc"
	this.Dir = &dir
	return &this
}

// GetColumn returns the Column field value
func (o *TablesAliasRowsQueryPostRequestSortInner) GetColumn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Column
}

// GetColumnOk returns a tuple with the Column field value
// and a boolean to check if the value has been set.
func (o *TablesAliasRowsQueryPostRequestSortInner) GetColumnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Column, true
}

// SetColumn sets field value
func (o *TablesAliasRowsQueryPostRequestSortInner) SetColumn(v string) {
	o.Column = v
}

// GetDir returns the Dir field value if set, zero value otherwise.
func (o *TablesAliasRowsQueryPostRequestSortInner) GetDir() string {
	if o == nil || IsNil(o.Dir) {
		var ret string
		return ret
	}
	return *o.Dir
}

// GetDirOk returns a tuple with the Dir field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TablesAliasRowsQueryPostRequestSortInner) GetDirOk() (*string, bool) {
	if o == nil || IsNil(o.Dir) {
		return nil, false
	}
	return o.Dir, true
}

// HasDir returns a boolean if a field has been set.
func (o *TablesAliasRowsQueryPostRequestSortInner) HasDir() bool {
	if o != nil && !IsNil(o.Dir) {
		return true
	}

	return false
}

// SetDir gets a reference to the given string and assigns it to the Dir field.
func (o *TablesAliasRowsQueryPostRequestSortInner) SetDir(v string) {
	o.Dir = &v
}

func (o TablesAliasRowsQueryPostRequestSortInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TablesAliasRowsQueryPostRequestSortInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["column"] = o.Column
	if !IsNil(o.Dir) {
		toSerialize["dir"] = o.Dir
	}
	return toSerialize, nil
}

func (o *TablesAliasRowsQueryPostRequestSortInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"column",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTablesAliasRowsQueryPostRequestSortInner := _TablesAliasRowsQueryPostRequestSortInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTablesAliasRowsQueryPostRequestSortInner)

	if err != nil {
		return err
	}

	*o = TablesAliasRowsQueryPostRequestSortInner(varTablesAliasRowsQueryPostRequestSortInner)

	return err
}

type NullableTablesAliasRowsQueryPostRequestSortInner struct {
	value *TablesAliasRowsQueryPostRequestSortInner
	isSet bool
}

func (v NullableTablesAliasRowsQueryPostRequestSortInner) Get() *TablesAliasRowsQueryPostRequestSortInner {
	return v.value
}

func (v *NullableTablesAliasRowsQueryPostRequestSortInner) Set(val *TablesAliasRowsQueryPostRequestSortInner) {
	v.value = val
	v.isSet = true
}

func (v NullableTablesAliasRowsQueryPostRequestSortInner) IsSet() bool {
	return v.isSet
}

func (v *NullableTablesAliasRowsQueryPostRequestSortInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTablesAliasRowsQueryPostRequestSortInner(val *TablesAliasRowsQueryPostRequestSortInner) *NullableTablesAliasRowsQueryPostRequestSortInner {
	return &NullableTablesAliasRowsQueryPostRequestSortInner{value: val, isSet: true}
}

func (v NullableTablesAliasRowsQueryPostRequestSortInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTablesAliasRowsQueryPostRequestSortInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


