/*
River REST API

Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 

API version: 0.10.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rivergo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FilesPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FilesPostRequest{}

// FilesPostRequest struct for FilesPostRequest
type FilesPostRequest struct {
	Name string `json:"name"`
	// parent node id
	Parent *string `json:"parent,omitempty"`
}

type _FilesPostRequest FilesPostRequest

// NewFilesPostRequest instantiates a new FilesPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFilesPostRequest(name string) *FilesPostRequest {
	this := FilesPostRequest{}
	this.Name = name
	return &this
}

// NewFilesPostRequestWithDefaults instantiates a new FilesPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFilesPostRequestWithDefaults() *FilesPostRequest {
	this := FilesPostRequest{}
	return &this
}

// GetName returns the Name field value
func (o *FilesPostRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *FilesPostRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *FilesPostRequest) SetName(v string) {
	o.Name = v
}

// GetParent returns the Parent field value if set, zero value otherwise.
func (o *FilesPostRequest) GetParent() string {
	if o == nil || IsNil(o.Parent) {
		var ret string
		return ret
	}
	return *o.Parent
}

// GetParentOk returns a tuple with the Parent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilesPostRequest) GetParentOk() (*string, bool) {
	if o == nil || IsNil(o.Parent) {
		return nil, false
	}
	return o.Parent, true
}

// HasParent returns a boolean if a field has been set.
func (o *FilesPostRequest) HasParent() bool {
	if o != nil && !IsNil(o.Parent) {
		return true
	}

	return false
}

// SetParent gets a reference to the given string and assigns it to the Parent field.
func (o *FilesPostRequest) SetParent(v string) {
	o.Parent = &v
}

func (o FilesPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FilesPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Parent) {
		toSerialize["parent"] = o.Parent
	}
	return toSerialize, nil
}

func (o *FilesPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFilesPostRequest := _FilesPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFilesPostRequest)

	if err != nil {
		return err
	}

	*o = FilesPostRequest(varFilesPostRequest)

	return err
}

type NullableFilesPostRequest struct {
	value *FilesPostRequest
	isSet bool
}

func (v NullableFilesPostRequest) Get() *FilesPostRequest {
	return v.value
}

func (v *NullableFilesPostRequest) Set(val *FilesPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableFilesPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableFilesPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFilesPostRequest(val *FilesPostRequest) *NullableFilesPostRequest {
	return &NullableFilesPostRequest{value: val, isSet: true}
}

func (v NullableFilesPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFilesPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


