/*
River REST API

Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 

API version: 0.9.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rivergo

import (
	"encoding/json"
)

// checks if the DesignerDesignsIdPublishPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DesignerDesignsIdPublishPostRequest{}

// DesignerDesignsIdPublishPostRequest struct for DesignerDesignsIdPublishPostRequest
type DesignerDesignsIdPublishPostRequest struct {
	Notes *string `json:"notes,omitempty"`
	ConfirmDestructive *bool `json:"confirm_destructive,omitempty"`
	Dialect *string `json:"dialect,omitempty"`
}

// NewDesignerDesignsIdPublishPostRequest instantiates a new DesignerDesignsIdPublishPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDesignerDesignsIdPublishPostRequest() *DesignerDesignsIdPublishPostRequest {
	this := DesignerDesignsIdPublishPostRequest{}
	var confirmDestructive bool = false
	this.ConfirmDestructive = &confirmDestructive
	return &this
}

// NewDesignerDesignsIdPublishPostRequestWithDefaults instantiates a new DesignerDesignsIdPublishPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDesignerDesignsIdPublishPostRequestWithDefaults() *DesignerDesignsIdPublishPostRequest {
	this := DesignerDesignsIdPublishPostRequest{}
	var confirmDestructive bool = false
	this.ConfirmDestructive = &confirmDestructive
	return &this
}

// GetNotes returns the Notes field value if set, zero value otherwise.
func (o *DesignerDesignsIdPublishPostRequest) GetNotes() string {
	if o == nil || IsNil(o.Notes) {
		var ret string
		return ret
	}
	return *o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DesignerDesignsIdPublishPostRequest) GetNotesOk() (*string, bool) {
	if o == nil || IsNil(o.Notes) {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *DesignerDesignsIdPublishPostRequest) HasNotes() bool {
	if o != nil && !IsNil(o.Notes) {
		return true
	}

	return false
}

// SetNotes gets a reference to the given string and assigns it to the Notes field.
func (o *DesignerDesignsIdPublishPostRequest) SetNotes(v string) {
	o.Notes = &v
}

// GetConfirmDestructive returns the ConfirmDestructive field value if set, zero value otherwise.
func (o *DesignerDesignsIdPublishPostRequest) GetConfirmDestructive() bool {
	if o == nil || IsNil(o.ConfirmDestructive) {
		var ret bool
		return ret
	}
	return *o.ConfirmDestructive
}

// GetConfirmDestructiveOk returns a tuple with the ConfirmDestructive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DesignerDesignsIdPublishPostRequest) GetConfirmDestructiveOk() (*bool, bool) {
	if o == nil || IsNil(o.ConfirmDestructive) {
		return nil, false
	}
	return o.ConfirmDestructive, true
}

// HasConfirmDestructive returns a boolean if a field has been set.
func (o *DesignerDesignsIdPublishPostRequest) HasConfirmDestructive() bool {
	if o != nil && !IsNil(o.ConfirmDestructive) {
		return true
	}

	return false
}

// SetConfirmDestructive gets a reference to the given bool and assigns it to the ConfirmDestructive field.
func (o *DesignerDesignsIdPublishPostRequest) SetConfirmDestructive(v bool) {
	o.ConfirmDestructive = &v
}

// GetDialect returns the Dialect field value if set, zero value otherwise.
func (o *DesignerDesignsIdPublishPostRequest) GetDialect() string {
	if o == nil || IsNil(o.Dialect) {
		var ret string
		return ret
	}
	return *o.Dialect
}

// GetDialectOk returns a tuple with the Dialect field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DesignerDesignsIdPublishPostRequest) GetDialectOk() (*string, bool) {
	if o == nil || IsNil(o.Dialect) {
		return nil, false
	}
	return o.Dialect, true
}

// HasDialect returns a boolean if a field has been set.
func (o *DesignerDesignsIdPublishPostRequest) HasDialect() bool {
	if o != nil && !IsNil(o.Dialect) {
		return true
	}

	return false
}

// SetDialect gets a reference to the given string and assigns it to the Dialect field.
func (o *DesignerDesignsIdPublishPostRequest) SetDialect(v string) {
	o.Dialect = &v
}

func (o DesignerDesignsIdPublishPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DesignerDesignsIdPublishPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Notes) {
		toSerialize["notes"] = o.Notes
	}
	if !IsNil(o.ConfirmDestructive) {
		toSerialize["confirm_destructive"] = o.ConfirmDestructive
	}
	if !IsNil(o.Dialect) {
		toSerialize["dialect"] = o.Dialect
	}
	return toSerialize, nil
}

type NullableDesignerDesignsIdPublishPostRequest struct {
	value *DesignerDesignsIdPublishPostRequest
	isSet bool
}

func (v NullableDesignerDesignsIdPublishPostRequest) Get() *DesignerDesignsIdPublishPostRequest {
	return v.value
}

func (v *NullableDesignerDesignsIdPublishPostRequest) Set(val *DesignerDesignsIdPublishPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDesignerDesignsIdPublishPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDesignerDesignsIdPublishPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDesignerDesignsIdPublishPostRequest(val *DesignerDesignsIdPublishPostRequest) *NullableDesignerDesignsIdPublishPostRequest {
	return &NullableDesignerDesignsIdPublishPostRequest{value: val, isSet: true}
}

func (v NullableDesignerDesignsIdPublishPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDesignerDesignsIdPublishPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


