/*
River REST API

Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 

API version: 0.9.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rivergo

import (
	"encoding/json"
)

// checks if the TableRows type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TableRows{}

// TableRows one page of a table's rows, shaped for the dashboard datagrid
type TableRows struct {
	Columns []TableColumnMeta `json:"columns,omitempty"`
	Rows [][]interface{} `json:"rows,omitempty"`
	// primary-key columns; empty → existing rows are read-only (D54)
	KeyColumns []string `json:"key_columns,omitempty"`
	Editable *bool `json:"editable,omitempty"`
	Limit *int32 `json:"limit,omitempty"`
	Offset *int32 `json:"offset,omitempty"`
	HasMore *bool `json:"has_more,omitempty"`
	// present only when count=true was requested
	Total NullableInt32 `json:"total,omitempty"`
	Strategy *string `json:"strategy,omitempty"`
	DurationMs *float32 `json:"duration_ms,omitempty"`
}

// NewTableRows instantiates a new TableRows object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTableRows() *TableRows {
	this := TableRows{}
	return &this
}

// NewTableRowsWithDefaults instantiates a new TableRows object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTableRowsWithDefaults() *TableRows {
	this := TableRows{}
	return &this
}

// GetColumns returns the Columns field value if set, zero value otherwise.
func (o *TableRows) GetColumns() []TableColumnMeta {
	if o == nil || IsNil(o.Columns) {
		var ret []TableColumnMeta
		return ret
	}
	return o.Columns
}

// GetColumnsOk returns a tuple with the Columns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TableRows) GetColumnsOk() ([]TableColumnMeta, bool) {
	if o == nil || IsNil(o.Columns) {
		return nil, false
	}
	return o.Columns, true
}

// HasColumns returns a boolean if a field has been set.
func (o *TableRows) HasColumns() bool {
	if o != nil && !IsNil(o.Columns) {
		return true
	}

	return false
}

// SetColumns gets a reference to the given []TableColumnMeta and assigns it to the Columns field.
func (o *TableRows) SetColumns(v []TableColumnMeta) {
	o.Columns = v
}

// GetRows returns the Rows field value if set, zero value otherwise.
func (o *TableRows) GetRows() [][]interface{} {
	if o == nil || IsNil(o.Rows) {
		var ret [][]interface{}
		return ret
	}
	return o.Rows
}

// GetRowsOk returns a tuple with the Rows field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TableRows) GetRowsOk() ([][]interface{}, bool) {
	if o == nil || IsNil(o.Rows) {
		return nil, false
	}
	return o.Rows, true
}

// HasRows returns a boolean if a field has been set.
func (o *TableRows) HasRows() bool {
	if o != nil && !IsNil(o.Rows) {
		return true
	}

	return false
}

// SetRows gets a reference to the given [][]interface{} and assigns it to the Rows field.
func (o *TableRows) SetRows(v [][]interface{}) {
	o.Rows = v
}

// GetKeyColumns returns the KeyColumns field value if set, zero value otherwise.
func (o *TableRows) GetKeyColumns() []string {
	if o == nil || IsNil(o.KeyColumns) {
		var ret []string
		return ret
	}
	return o.KeyColumns
}

// GetKeyColumnsOk returns a tuple with the KeyColumns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TableRows) GetKeyColumnsOk() ([]string, bool) {
	if o == nil || IsNil(o.KeyColumns) {
		return nil, false
	}
	return o.KeyColumns, true
}

// HasKeyColumns returns a boolean if a field has been set.
func (o *TableRows) HasKeyColumns() bool {
	if o != nil && !IsNil(o.KeyColumns) {
		return true
	}

	return false
}

// SetKeyColumns gets a reference to the given []string and assigns it to the KeyColumns field.
func (o *TableRows) SetKeyColumns(v []string) {
	o.KeyColumns = v
}

// GetEditable returns the Editable field value if set, zero value otherwise.
func (o *TableRows) GetEditable() bool {
	if o == nil || IsNil(o.Editable) {
		var ret bool
		return ret
	}
	return *o.Editable
}

// GetEditableOk returns a tuple with the Editable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TableRows) GetEditableOk() (*bool, bool) {
	if o == nil || IsNil(o.Editable) {
		return nil, false
	}
	return o.Editable, true
}

// HasEditable returns a boolean if a field has been set.
func (o *TableRows) HasEditable() bool {
	if o != nil && !IsNil(o.Editable) {
		return true
	}

	return false
}

// SetEditable gets a reference to the given bool and assigns it to the Editable field.
func (o *TableRows) SetEditable(v bool) {
	o.Editable = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *TableRows) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TableRows) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *TableRows) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *TableRows) SetLimit(v int32) {
	o.Limit = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *TableRows) GetOffset() int32 {
	if o == nil || IsNil(o.Offset) {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TableRows) GetOffsetOk() (*int32, bool) {
	if o == nil || IsNil(o.Offset) {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *TableRows) HasOffset() bool {
	if o != nil && !IsNil(o.Offset) {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *TableRows) SetOffset(v int32) {
	o.Offset = &v
}

// GetHasMore returns the HasMore field value if set, zero value otherwise.
func (o *TableRows) GetHasMore() bool {
	if o == nil || IsNil(o.HasMore) {
		var ret bool
		return ret
	}
	return *o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TableRows) GetHasMoreOk() (*bool, bool) {
	if o == nil || IsNil(o.HasMore) {
		return nil, false
	}
	return o.HasMore, true
}

// HasHasMore returns a boolean if a field has been set.
func (o *TableRows) HasHasMore() bool {
	if o != nil && !IsNil(o.HasMore) {
		return true
	}

	return false
}

// SetHasMore gets a reference to the given bool and assigns it to the HasMore field.
func (o *TableRows) SetHasMore(v bool) {
	o.HasMore = &v
}

// GetTotal returns the Total field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TableRows) GetTotal() int32 {
	if o == nil || IsNil(o.Total.Get()) {
		var ret int32
		return ret
	}
	return *o.Total.Get()
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TableRows) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Total.Get(), o.Total.IsSet()
}

// HasTotal returns a boolean if a field has been set.
func (o *TableRows) HasTotal() bool {
	if o != nil && o.Total.IsSet() {
		return true
	}

	return false
}

// SetTotal gets a reference to the given NullableInt32 and assigns it to the Total field.
func (o *TableRows) SetTotal(v int32) {
	o.Total.Set(&v)
}
// SetTotalNil sets the value for Total to be an explicit nil
func (o *TableRows) SetTotalNil() {
	o.Total.Set(nil)
}

// UnsetTotal ensures that no value is present for Total, not even an explicit nil
func (o *TableRows) UnsetTotal() {
	o.Total.Unset()
}

// GetStrategy returns the Strategy field value if set, zero value otherwise.
func (o *TableRows) GetStrategy() string {
	if o == nil || IsNil(o.Strategy) {
		var ret string
		return ret
	}
	return *o.Strategy
}

// GetStrategyOk returns a tuple with the Strategy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TableRows) GetStrategyOk() (*string, bool) {
	if o == nil || IsNil(o.Strategy) {
		return nil, false
	}
	return o.Strategy, true
}

// HasStrategy returns a boolean if a field has been set.
func (o *TableRows) HasStrategy() bool {
	if o != nil && !IsNil(o.Strategy) {
		return true
	}

	return false
}

// SetStrategy gets a reference to the given string and assigns it to the Strategy field.
func (o *TableRows) SetStrategy(v string) {
	o.Strategy = &v
}

// GetDurationMs returns the DurationMs field value if set, zero value otherwise.
func (o *TableRows) GetDurationMs() float32 {
	if o == nil || IsNil(o.DurationMs) {
		var ret float32
		return ret
	}
	return *o.DurationMs
}

// GetDurationMsOk returns a tuple with the DurationMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TableRows) GetDurationMsOk() (*float32, bool) {
	if o == nil || IsNil(o.DurationMs) {
		return nil, false
	}
	return o.DurationMs, true
}

// HasDurationMs returns a boolean if a field has been set.
func (o *TableRows) HasDurationMs() bool {
	if o != nil && !IsNil(o.DurationMs) {
		return true
	}

	return false
}

// SetDurationMs gets a reference to the given float32 and assigns it to the DurationMs field.
func (o *TableRows) SetDurationMs(v float32) {
	o.DurationMs = &v
}

func (o TableRows) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TableRows) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Columns) {
		toSerialize["columns"] = o.Columns
	}
	if !IsNil(o.Rows) {
		toSerialize["rows"] = o.Rows
	}
	if !IsNil(o.KeyColumns) {
		toSerialize["key_columns"] = o.KeyColumns
	}
	if !IsNil(o.Editable) {
		toSerialize["editable"] = o.Editable
	}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.Offset) {
		toSerialize["offset"] = o.Offset
	}
	if !IsNil(o.HasMore) {
		toSerialize["has_more"] = o.HasMore
	}
	if o.Total.IsSet() {
		toSerialize["total"] = o.Total.Get()
	}
	if !IsNil(o.Strategy) {
		toSerialize["strategy"] = o.Strategy
	}
	if !IsNil(o.DurationMs) {
		toSerialize["duration_ms"] = o.DurationMs
	}
	return toSerialize, nil
}

type NullableTableRows struct {
	value *TableRows
	isSet bool
}

func (v NullableTableRows) Get() *TableRows {
	return v.value
}

func (v *NullableTableRows) Set(val *TableRows) {
	v.value = val
	v.isSet = true
}

func (v NullableTableRows) IsSet() bool {
	return v.isSet
}

func (v *NullableTableRows) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTableRows(val *TableRows) *NullableTableRows {
	return &NullableTableRows{value: val, isSet: true}
}

func (v NullableTableRows) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTableRows) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


