/*
River REST API

Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 

API version: 0.9.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rivergo

import (
	"encoding/json"
)

// checks if the AiSummarizePostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AiSummarizePostRequest{}

// AiSummarizePostRequest struct for AiSummarizePostRequest
type AiSummarizePostRequest struct {
	Columns []string `json:"columns,omitempty"`
	Rows [][]interface{} `json:"rows,omitempty"`
	TotalRowCount *int32 `json:"total_row_count,omitempty"`
}

// NewAiSummarizePostRequest instantiates a new AiSummarizePostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAiSummarizePostRequest() *AiSummarizePostRequest {
	this := AiSummarizePostRequest{}
	return &this
}

// NewAiSummarizePostRequestWithDefaults instantiates a new AiSummarizePostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAiSummarizePostRequestWithDefaults() *AiSummarizePostRequest {
	this := AiSummarizePostRequest{}
	return &this
}

// GetColumns returns the Columns field value if set, zero value otherwise.
func (o *AiSummarizePostRequest) GetColumns() []string {
	if o == nil || IsNil(o.Columns) {
		var ret []string
		return ret
	}
	return o.Columns
}

// GetColumnsOk returns a tuple with the Columns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiSummarizePostRequest) GetColumnsOk() ([]string, bool) {
	if o == nil || IsNil(o.Columns) {
		return nil, false
	}
	return o.Columns, true
}

// HasColumns returns a boolean if a field has been set.
func (o *AiSummarizePostRequest) HasColumns() bool {
	if o != nil && !IsNil(o.Columns) {
		return true
	}

	return false
}

// SetColumns gets a reference to the given []string and assigns it to the Columns field.
func (o *AiSummarizePostRequest) SetColumns(v []string) {
	o.Columns = v
}

// GetRows returns the Rows field value if set, zero value otherwise.
func (o *AiSummarizePostRequest) GetRows() [][]interface{} {
	if o == nil || IsNil(o.Rows) {
		var ret [][]interface{}
		return ret
	}
	return o.Rows
}

// GetRowsOk returns a tuple with the Rows field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiSummarizePostRequest) GetRowsOk() ([][]interface{}, bool) {
	if o == nil || IsNil(o.Rows) {
		return nil, false
	}
	return o.Rows, true
}

// HasRows returns a boolean if a field has been set.
func (o *AiSummarizePostRequest) HasRows() bool {
	if o != nil && !IsNil(o.Rows) {
		return true
	}

	return false
}

// SetRows gets a reference to the given [][]interface{} and assigns it to the Rows field.
func (o *AiSummarizePostRequest) SetRows(v [][]interface{}) {
	o.Rows = v
}

// GetTotalRowCount returns the TotalRowCount field value if set, zero value otherwise.
func (o *AiSummarizePostRequest) GetTotalRowCount() int32 {
	if o == nil || IsNil(o.TotalRowCount) {
		var ret int32
		return ret
	}
	return *o.TotalRowCount
}

// GetTotalRowCountOk returns a tuple with the TotalRowCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiSummarizePostRequest) GetTotalRowCountOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalRowCount) {
		return nil, false
	}
	return o.TotalRowCount, true
}

// HasTotalRowCount returns a boolean if a field has been set.
func (o *AiSummarizePostRequest) HasTotalRowCount() bool {
	if o != nil && !IsNil(o.TotalRowCount) {
		return true
	}

	return false
}

// SetTotalRowCount gets a reference to the given int32 and assigns it to the TotalRowCount field.
func (o *AiSummarizePostRequest) SetTotalRowCount(v int32) {
	o.TotalRowCount = &v
}

func (o AiSummarizePostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AiSummarizePostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Columns) {
		toSerialize["columns"] = o.Columns
	}
	if !IsNil(o.Rows) {
		toSerialize["rows"] = o.Rows
	}
	if !IsNil(o.TotalRowCount) {
		toSerialize["total_row_count"] = o.TotalRowCount
	}
	return toSerialize, nil
}

type NullableAiSummarizePostRequest struct {
	value *AiSummarizePostRequest
	isSet bool
}

func (v NullableAiSummarizePostRequest) Get() *AiSummarizePostRequest {
	return v.value
}

func (v *NullableAiSummarizePostRequest) Set(val *AiSummarizePostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAiSummarizePostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAiSummarizePostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAiSummarizePostRequest(val *AiSummarizePostRequest) *NullableAiSummarizePostRequest {
	return &NullableAiSummarizePostRequest{value: val, isSet: true}
}

func (v NullableAiSummarizePostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAiSummarizePostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


