/*
River REST API

Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 

API version: 0.9.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rivergo

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TileData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TileData{}

// TileData one tile's slice of the /data response
type TileData struct {
	Index int32 `json:"index"`
	Status string `json:"status"`
	Cached bool `json:"cached"`
	ElapsedMs float32 `json:"elapsed_ms"`
	// named params the tile binds (also present on bind errors)
	Params []string `json:"params,omitempty"`
	Result *QueryResult `json:"result,omitempty"`
	Error *string `json:"error,omitempty"`
}

type _TileData TileData

// NewTileData instantiates a new TileData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTileData(index int32, status string, cached bool, elapsedMs float32) *TileData {
	this := TileData{}
	this.Index = index
	this.Status = status
	this.Cached = cached
	this.ElapsedMs = elapsedMs
	return &this
}

// NewTileDataWithDefaults instantiates a new TileData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTileDataWithDefaults() *TileData {
	this := TileData{}
	return &this
}

// GetIndex returns the Index field value
func (o *TileData) GetIndex() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Index
}

// GetIndexOk returns a tuple with the Index field value
// and a boolean to check if the value has been set.
func (o *TileData) GetIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Index, true
}

// SetIndex sets field value
func (o *TileData) SetIndex(v int32) {
	o.Index = v
}

// GetStatus returns the Status field value
func (o *TileData) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *TileData) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *TileData) SetStatus(v string) {
	o.Status = v
}

// GetCached returns the Cached field value
func (o *TileData) GetCached() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Cached
}

// GetCachedOk returns a tuple with the Cached field value
// and a boolean to check if the value has been set.
func (o *TileData) GetCachedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cached, true
}

// SetCached sets field value
func (o *TileData) SetCached(v bool) {
	o.Cached = v
}

// GetElapsedMs returns the ElapsedMs field value
func (o *TileData) GetElapsedMs() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ElapsedMs
}

// GetElapsedMsOk returns a tuple with the ElapsedMs field value
// and a boolean to check if the value has been set.
func (o *TileData) GetElapsedMsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ElapsedMs, true
}

// SetElapsedMs sets field value
func (o *TileData) SetElapsedMs(v float32) {
	o.ElapsedMs = v
}

// GetParams returns the Params field value if set, zero value otherwise.
func (o *TileData) GetParams() []string {
	if o == nil || IsNil(o.Params) {
		var ret []string
		return ret
	}
	return o.Params
}

// GetParamsOk returns a tuple with the Params field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TileData) GetParamsOk() ([]string, bool) {
	if o == nil || IsNil(o.Params) {
		return nil, false
	}
	return o.Params, true
}

// HasParams returns a boolean if a field has been set.
func (o *TileData) HasParams() bool {
	if o != nil && !IsNil(o.Params) {
		return true
	}

	return false
}

// SetParams gets a reference to the given []string and assigns it to the Params field.
func (o *TileData) SetParams(v []string) {
	o.Params = v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *TileData) GetResult() QueryResult {
	if o == nil || IsNil(o.Result) {
		var ret QueryResult
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TileData) GetResultOk() (*QueryResult, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *TileData) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given QueryResult and assigns it to the Result field.
func (o *TileData) SetResult(v QueryResult) {
	o.Result = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *TileData) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TileData) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *TileData) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *TileData) SetError(v string) {
	o.Error = &v
}

func (o TileData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TileData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["index"] = o.Index
	toSerialize["status"] = o.Status
	toSerialize["cached"] = o.Cached
	toSerialize["elapsed_ms"] = o.ElapsedMs
	if !IsNil(o.Params) {
		toSerialize["params"] = o.Params
	}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

func (o *TileData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"index",
		"status",
		"cached",
		"elapsed_ms",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTileData := _TileData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTileData)

	if err != nil {
		return err
	}

	*o = TileData(varTileData)

	return err
}

type NullableTileData struct {
	value *TileData
	isSet bool
}

func (v NullableTileData) Get() *TileData {
	return v.value
}

func (v *NullableTileData) Set(val *TileData) {
	v.value = val
	v.isSet = true
}

func (v NullableTileData) IsSet() bool {
	return v.isSet
}

func (v *NullableTileData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTileData(val *TileData) *NullableTileData {
	return &NullableTileData{value: val, isSet: true}
}

func (v NullableTileData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTileData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


