/*
River REST API

Cross-database SQL federation engine: River federation, Warden instance orchestration, query files, notebooks, the filestore (bucket volumes mounted at /home/river/rfs inside notebook runtimes) and the Lily AI. Source of truth for route shapes is `src/api.rs` — this spec tracks it, schemas are indicative. Auth: a `Bearer <jwt>` from /auth/register|login|refresh, an `x-api-key` `rqk_…` key issued post-login, or an operator-configured static key (bootstrap org). Public (no auth): `/v1/health`, `/`, `/v1/ai/status`, `/v1/auth/login|register|refresh`. Everything else is 401 fail-closed and RBAC-gated (`module:resource:action` permissions per org role). 

API version: 0.10.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rivergo

import (
	"encoding/json"
)

// checks if the ArchiveEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ArchiveEntry{}

// ArchiveEntry struct for ArchiveEntry
type ArchiveEntry struct {
	Name *string `json:"name,omitempty"`
	SizeBytes *int32 `json:"size_bytes,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
}

// NewArchiveEntry instantiates a new ArchiveEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArchiveEntry() *ArchiveEntry {
	this := ArchiveEntry{}
	return &this
}

// NewArchiveEntryWithDefaults instantiates a new ArchiveEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArchiveEntryWithDefaults() *ArchiveEntry {
	this := ArchiveEntry{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ArchiveEntry) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArchiveEntry) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ArchiveEntry) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ArchiveEntry) SetName(v string) {
	o.Name = &v
}

// GetSizeBytes returns the SizeBytes field value if set, zero value otherwise.
func (o *ArchiveEntry) GetSizeBytes() int32 {
	if o == nil || IsNil(o.SizeBytes) {
		var ret int32
		return ret
	}
	return *o.SizeBytes
}

// GetSizeBytesOk returns a tuple with the SizeBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArchiveEntry) GetSizeBytesOk() (*int32, bool) {
	if o == nil || IsNil(o.SizeBytes) {
		return nil, false
	}
	return o.SizeBytes, true
}

// HasSizeBytes returns a boolean if a field has been set.
func (o *ArchiveEntry) HasSizeBytes() bool {
	if o != nil && !IsNil(o.SizeBytes) {
		return true
	}

	return false
}

// SetSizeBytes gets a reference to the given int32 and assigns it to the SizeBytes field.
func (o *ArchiveEntry) SetSizeBytes(v int32) {
	o.SizeBytes = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ArchiveEntry) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArchiveEntry) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ArchiveEntry) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *ArchiveEntry) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

func (o ArchiveEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ArchiveEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.SizeBytes) {
		toSerialize["size_bytes"] = o.SizeBytes
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	return toSerialize, nil
}

type NullableArchiveEntry struct {
	value *ArchiveEntry
	isSet bool
}

func (v NullableArchiveEntry) Get() *ArchiveEntry {
	return v.value
}

func (v *NullableArchiveEntry) Set(val *ArchiveEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableArchiveEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableArchiveEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArchiveEntry(val *ArchiveEntry) *NullableArchiveEntry {
	return &NullableArchiveEntry{value: val, isSet: true}
}

func (v NullableArchiveEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArchiveEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


